(********************************************************************
 * COPYRIGHT -- B&R
 ********************************************************************
 * Library: AsHydCon
 * File: AsHydCon.typ
 * Author: DI Thomas J. Frauscher
 * Created: July 2011
 ********************************************************************
 * Data types of library AsHydCon
 ********************************************************************)

TYPE
	HCRSystemPara_typ : 	STRUCT  (*System parameters.*)
		pSupply_max : REAL; (*Maximum system pressure (supply pressure). Units: [bar]. Valid value range: pSupply_max >= 0.*)
		pSupply : REAL; (*System pressure (supply pressure). Units: [bar]. Valid value range: pSupply > 0.*)
		pTank : REAL; (*Tank pressure. Units: [bar]. Valid value range: pTank >= 0.*)
		A_Cyl_pos : REAL; (*Cylinder piston area whose pressurization induces a movement in the positive direction (e.g. extending piston). Units: [cm?]. Valid value range: A_Cyl_pos > 0.*)
		A_Cyl_neg : REAL; (*Cylinder piston area whose pressurization induces a movement in the negative direction (e.g. retracting piston). Units: [cm?]. Valid value range: A_Cyl_neg > 0.*)
	END_STRUCT;
	HCRSystemParaAdd_typ : 	STRUCT  (*Additional system parameters.*)
		V0_pos : REAL; (*Static volume in reference to the cylinder chamber responsible for movement in the 'positive' direction (e.g. extending piston). Units: [l]. Valid value range: V0_pos >= 0.*)
		V0_neg : REAL; (*Static volume in reference to the cylinder chamber responsible for movement in the 'negative' direction (e.g. retracting piston). Units: [l]. Valid value range: V0_neg >= 0.*)
		h_Cyl : REAL; (*Cylinder height. Units: [mm]. Valid value range: h_Cyl > 0.*)
		m_Cyl : REAL; (*Resulting mass of the moving hydraulic system. Units: [kg]. Valid value range: m_Cyl > 0.*)
	END_STRUCT;
	HCRValvePara_typ : 	STRUCT  (*Valve parameters.*)
		Qnom_pos : REAL; (*Nominal valve volume flow, which, together with A_Cyl_pos results in a movement in the positive direction (e.g. extending piston). Units: [l/min]. Valid value range: Qnom_pos > 0.*)
		Qnom_neg : REAL; (*Nominal valve volume flow, which, together with A_Cyl_neg results in a movement in the negative direction (e.g. retracting piston). Units: [l/min]. Valid value range: Qnom_neg > 0.*)
		pDelta_nom : REAL; (*Nominal pressure drop at valve edge. Units: [bar]. Valid value range: pDelta_nom > 0.*)
		yValve_0 : REAL; (*Valve overlap. Units: [1]. Valid value range:  0 <= yValve_0 < 1.*)
		Neg_y : BOOL; (*Negative values for the valve opening yValve result in a positive speed, and vice versa (inverted valve behavior).*)
	END_STRUCT;
	HCRMovePara_typ : 	STRUCT  (*Movement parameters.*)
		t_Jolt : REAL; (*Jolt time. Units [s]. Valid value range: 0 <= t_Jolt <= 0.2.*)
		vC_pos : REAL; (*Maximum speed of motion in the 'positive' direction. Units [mm/s]. Valid value range: vC_pos > 0.*)
		vC_neg : REAL; (*Maximum speed of motion in the 'negative' direction. Units [mm/s]. Valid value range: vC_neg > 0.*)
		aAcc_pos : REAL; (*Acceleration in the 'positive' direction. Units [mm/s2]. Valid value range: aAcc_pos > 0.*)
		aDec_pos : REAL; (*Deceleration in the 'positive' direction. Units [mm/s2]. Valid value range: aDec_pos > 0.*)
		aAcc_neg : REAL; (*Acceleration in the 'negative' direction. Units [mm/s2]. Valid value range: aAcc_neg > 0.*)
		aDec_neg : REAL; (*Deceleration in the 'negative' direction. Units [mm/s2]. Valid value range: aDec_neg > 0.*)
	END_STRUCT;
	HCRNode_typ : 	STRUCT  (*Linearization node.*)
		X : REAL; (*x coordinate of a node of the node vector.*)
		Y : REAL; (*y coordinate of a node of the node vector.*)
		Internal : HCRNode_Internal_typ; (*Data for internal use.*)
	END_STRUCT;
	HCRPIDPara_typ : 	STRUCT  (*PID parameters.*)
		WX_min : REAL; (*Minimum value of reference variable and controlled variable. Valid value range: WX_min < WX_max.*)
		WX_max : REAL; (*Maximum value of reference variable and controlled variable. Valid value range: WX_max > WX_min.*)
		Kw : REAL; (*Set value attenuation. Units: [1]. Valid value range: 0 <= Kw <= 1.*)
		Kp : REAL; (*Proportional gain. Units: [1].*)
		Tn_pos : REAL; (*Integration time constant (integral action time) for I_Switch > 0. Units: [s]. Valid value range: Tn_pos >= 0.*)
		Tn_neg : REAL; (*Integration time constant (integral action time) for I_Switch < 0. Units: [s]. Valid value range: Tn_neg >= 0.*)
		K_Fbk : REAL; (*Windup damping. Units: [1]. Valid value range: K_Fbk >= 0.*)
		d_mode : USINT; (*Differentiation mode. Valid value range: {00000000, ..., 00001011}.*)
		Tv : REAL; (*Differentiation time constant (derivative action time) of the differentiator. Units: [s]. Valid value range: Tv >= 0.*)
		Tf : REAL; (*Filter time constant of the differentiator. Units: [s]. Valid value range: Tf >= 0.*)
		dY_max : REAL; (*Maximum manipulated variable ramp (rate of change of the manipulated variable). Units: [%/s]. Valid value range: dY_max >= 0.*)
		Y_min : REAL; (*Lower manipulated variable limit (lower modulation limit of the subsequent actuator). Units: [%]. Valid value range: -100 <= Y_min < Y_max.*)
		Y_max : REAL; (*Upper manipulated variable limit (upper modulation limit of the subsequent actuator). Units: [%]. Valid value range: Y_min < Y_max <= 100.*)
	END_STRUCT;
	HCRPIDPara_s_typ : 	STRUCT  (*PID parameters of the position controller.*)
		s_min : REAL; (*Minimal value of set position and actual position. Units: [mm]. Valid value range: s_min < s_max.*)
		s_max : REAL; (*Maximum value of set position and actual position. Units: [mm]. Valid value range: s_max > s_min.*)
		Kw : REAL; (*Set value attenuation. Units: [1]. Valid value range: 0 <= Kw <= 1.*)
		Kp : REAL; (*Proportional gain. Units: [1].*)
		Tn_pos : REAL; (*Integration time constant (integral action time) for movements in a 'positive' direction. Units: [s]. Valid value range: Tn_pos >= 0.*)
		Tn_neg : REAL; (*Integration time constant (integral action time) for movements in a 'negative' direction. Units: [s]. Valid value range: Tn_neg >= 0.*)
		K_Fbk : REAL; (*Windup damping. Units: [1]. Valid value range: K_Fbk >= 0.*)
		d_mode : USINT; (*Differentiation mode. Valid value range: {00000000, ..., 00000111}.*)
		Tv : REAL; (*Differentiation time constant (derivative action time) of the differentiator. Units: [s]. Valid value range: Tv >= 0.*)
		Tf : REAL; (*Filter time constant of the differentiator. Units: [s]. Valid value range: Tf >= 0.*)
		dv_max : REAL; (*Maximum rate of change of the piston speed (acceleration). Units: [mm/s2]. Valid value range: dv_max >= 0.*)
		v_min : REAL; (*Lower limit for the piston speed. Units: [mm/s]. Valid value range: -vCyl_sup <= v_min < v_max.*)
		v_max : REAL; (*Upper limit for the piston speed. Units: [mm/s]. Valid value range: v_min < v_max <= vCyl_sup.*)
		UseAsSpeedCont : BOOL;
	END_STRUCT;
	HCRPIDPara_F_typ : 	STRUCT  (*PID parameters of the force controller.*)
		Fp_min : REAL; (*Minimal value of set force and actual force. Units: [N]. Valid value range: Fp_min < Fp_max.*)
		Fp_max : REAL; (*Maximum value of set force and actual force. Units: [N]. Valid value range: Fp_max > Fp_min.*)
		Kw : REAL; (*Set value attenuation. Units: [1]. Valid value range: 0 <= Kw <= 1.*)
		Kp : REAL; (*Proportional gain. Units: [1].*)
		Tn : REAL; (*Integral action time. Units: [s]. Valid value range: Tn >= 0.*)
		K_Fbk : REAL; (*Windup damping. Units: [1]. Valid value range: K_Fbk >= 0.*)
		d_mode : USINT; (*Differentiation mode. Valid value range: {00000000, ..., 00001011}.*)
		Tv : REAL; (*Differentiation time constant (derivative action time) of the differentiator. Units: [s]. Valid value range: Tv >= 0.*)
		Tf : REAL; (*Filter time constant of the differentiator. Units: [s]. Valid value range: Tf >= 0.*)
		dQ_max : REAL; (*Maximum volume flow change speed. Units: [l/min/s]. Valid value range: dQ_max >= 0.*)
		Q_min : REAL; (*The lower limit of the valve volume flow. Units: [l/min]. Valid value range: -Qnom_neg <= Q_min < Q_max.*)
		Q_max : REAL; (*The upper limit of the valve volume flow. Units: [l/min]. Valid value range: Q_min < Q_max <= Qnom_pos.*)
	END_STRUCT;
	HCRP2P_Cont_AddPar_typ : 	STRUCT  (*Additional control parameters and options of HCRP2P_Cont().*)
		Y_P2P_min : REAL; (*Lower manipulated variable limit. Units: [%]. Valid value range: -100 <= Y_P2P_min < Y_P2P_max.*)
		Y_P2P_max : REAL; (*Upper manipulated variable limit. Units: [%]. Valid value range: Y_P2P_min < Y_P2P_max <= 100.*)
		dY_max : REAL; (*Maximum manipulated variable ramp (rate of change of the manipulated variable). Units: [%/s]. Valid value range: dY_max >= 0.*)
		Tn_pos : REAL; (*Integration time constant (integral action time) for movements in a 'positive' direction. Units: [s]. Valid value range: Tn_pos >= 0.*)
		Tn_neg : REAL; (*Integration time constant (integral action time) for movements in a 'negative' direction. Units: [s]. Valid value range: Tn_neg >= 0.*)
		I_Switch : USINT; (*Switch for the I part. Valid value range: {0, 1, 2, 3, 4}.*)
		Tv : REAL; (*Differentiation time constant (derivative action time) of the differentiator. Units: [s]. Valid value range: Tv >= 0.*)
		Tf : REAL; (*Filter time constant of the differentiator. Units: [s]. Valid value range: Tf >= 0.*)
	END_STRUCT;
	HCRs_Cont_InVar_typ : 	STRUCT  (*Additional position controller based input values of HCRsF_Cont().*)
		I_Switch : USINT; (*Switch for the I part of the PID. Valid value range: {0, 1, 2, 3, 4}.*)
		v_man : REAL; (*Speed of movement in manual operation. Units: [mm/s]. Valid value range: v_min <= v_man <= v_max.*)
		v_add : REAL; (*Additional speed input. Units: [mm/s]. Valid value range: -vCyl_sup < v_add < vCyl_sup.*)
		v_set : REAL; (*Set speed for speed input control of the cylinder movement. Units: [mm/s]. Valid value range: -vCyl_sup < v_set < vCyl_sup.*)
		Fp_Cyl : REAL; (*Process force. Units: [N].*)
		Ff_Cyl_pos : REAL; (*Friction force in positive direction. Units: [N]. Valid value range:  Ff_Cyl_pos >= 0.*)
		Ff_Cyl_neg : REAL; (*Friction force in negative direction. Units: [N]. Valid value range:  Ff_Cyl_neg >= 0.*)
		Qy_Oset_ext : REAL; (*External volume flow offset. Units: [l/min].*)
		Oset_Mode : USINT; (*Selection switch for offset compensation. Valid value range: {00000000, ..., 01111111}.*)
	END_STRUCT;
	HCRs_Cont_p_InVar_typ : 	STRUCT  (*Additional position controller based input values of HCRsF_Cont_p().*)
		I_Switch : USINT; (*Switch for the I part of the PID. Valid value range: {0, 1, 2, 3, 4}.*)
		v_man : REAL; (*Speed of movement in manual operation. Units: [mm/s]. Valid value range: v_min <= v_man <= v_max.*)
		v_add : REAL; (*Additional speed input. Units: [mm/s]. Valid value range: -vCyl_sup < v_add < vCyl_sup.*)
		v_set : REAL; (*Set speed for speed input control of the cylinder movement. Units: [mm/s]. Valid value range: -vCyl_sup < v_set < vCyl_sup.*)
		pCyl_pos : REAL; (*Chamber pressure for movement in the 'positive' direction. Units: [bar]. Valid value range: 0 <= pCyl_pos < pSupply.*)
		pCyl_neg : REAL; (*Chamber pressure for movement in the 'negative' direction. Units: [bar]. Valid value range: 0 <= pCyl_neg < pSupply.*)
		Qy_Oset_ext : REAL; (*External volume flow offset. Units: [l/min].*)
		Oset_Mode : USINT; (*Selection switch for offset compensation. Valid value range: {00000000, ..., 01111111}.*)
	END_STRUCT;
	HCRF_Cont_InVar_typ : 	STRUCT  (*Additional force controller based input values of HCRsF_Cont().*)
		I_Switch : USINT; (*Switch for the I part of the PID. Valid value range: {0, 1, 2, 3, 4}.*)
		Q_man : REAL; (*Valve volume flow in manual operation. Units: [l/min]. Valid value range: -Q_min <= Q_man <= Q_max.*)
		Q_add : REAL; (*Additional volume flow input. Units: [l/min]. Valid value range: -Qnom_neg <= Q_add <= Qnom_pos.*)
		v_act : REAL; (*Actual speed of the cylinder piston. Units: [mm/s].*)
		Qy_Oset_ext : REAL; (*External volume flow offset. Units: [l/min].*)
		Oset_Mode : USINT; (*Selection switch for offset compensation. Valid value range: {00000000, ..., 01111111}.*)
	END_STRUCT;
	HCRF_Cont_p_InVar_typ : 	STRUCT  (*Additional force controller based input values of HCRsF_Cont_p().*)
		I_Switch : USINT; (*Switch for the I part of the PID. Valid value range: {0, 1, 2, 3, 4}.*)
		Q_man : REAL; (*Valve volume flow in manual operation. Units: [l/min]. Valid value range: -Q_min <= Q_man <= Q_max.*)
		Q_add : REAL; (*Additional volume flow input. Units: [l/min]. Valid value range: -Qnom_neg <= Q_add <= Qnom_pos.*)
		dFp_set : REAL; (*Set value of the rate of force increase of the cylinder. Units: [N/s].*)
		x_Cyl : REAL; (*Current position of the cylinder piston (always based on the cylinder). Units: [mm]. Valid value range: 0 <= x_Cyl <= h_Cyl.*)
		v_Cyl : REAL; (*Current speed of the cylinder piston (always based on the cylinder). Units: [mm/s].*)
		pCyl_pos : REAL; (*Chamber pressure for movement in the 'positive' direction. Units: [bar]. Valid value range: 0 <= pCyl_pos < pSupply.*)
		pCyl_neg : REAL; (*Chamber pressure for movement in the 'negative' direction. Units: [bar]. Valid value range: 0 <= pCyl_neg < pSupply.*)
		v_act : REAL; (*Actual speed of the cylinder piston. Units: [mm/s].*)
		Qy_Oset_ext : REAL; (*External volume flow offset. Units: [l/min].*)
		Oset_Mode : USINT; (*Selection switch for offset compensation. Valid value range: {00000000, ..., 01111111}.*)
	END_STRUCT;
	HCRPT1_Internal_typ : 	STRUCT  (*Internal variables of function block HCRPT1().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		V_old : REAL; (*Data for internal use.*)
		T1_old : REAL; (*Data for internal use.*)
		Set_y_old : USINT; (*Data for internal use.*)
		Set_y_2 : USINT; (*Data for internal use.*)
		x_dbl_1 : UDINT; (*Data for internal use.*)
		x_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_dbl_2 : UDINT; (*Data for internal use.*)
		V_Exp_dbl_1 : UDINT; (*Data for internal use.*)
		V_Exp_dbl_2 : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRPT2_Internal_typ : 	STRUCT  (*Internal variables of function block HCRPT2().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		V_old : REAL; (*Data for internal use.*)
		T1_old : REAL; (*Data for internal use.*)
		T2_old : REAL; (*Data for internal use.*)
		Set_y_old : USINT; (*Data for internal use.*)
		Set_y_2 : USINT; (*Data for internal use.*)
		x1_dbl_1 : UDINT; (*Data for internal use.*)
		x1_dbl_2 : UDINT; (*Data for internal use.*)
		x2_dbl_1 : UDINT; (*Data for internal use.*)
		x2_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_Ts_T2_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_Ts_T2_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_T2_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_T2_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_T1_T2_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_T1_T2_dbl_2 : UDINT; (*Data for internal use.*)
		V1_Exp_dbl_1 : UDINT; (*Data for internal use.*)
		V1_Exp_dbl_2 : UDINT; (*Data for internal use.*)
		V2_Exp_dbl_1 : UDINT; (*Data for internal use.*)
		V2_Exp_dbl_2 : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRPT2s_Internal_typ : 	STRUCT  (*Internal variables of function block HCRPT2s().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		V_old : REAL; (*Data for internal use.*)
		D_old : REAL; (*Data for internal use.*)
		Tf_old : REAL; (*Data for internal use.*)
		Set_y_old : USINT; (*Data for internal use.*)
		Set_y_2 : USINT; (*Data for internal use.*)
		x1_dbl_1 : UDINT; (*Data for internal use.*)
		x1_dbl_2 : UDINT; (*Data for internal use.*)
		x2_dbl_1 : UDINT; (*Data for internal use.*)
		x2_dbl_2 : UDINT; (*Data for internal use.*)
		Sqrt_D_1_dbl_1 : UDINT; (*Data for internal use.*)
		Sqrt_D_1_dbl_2 : UDINT; (*Data for internal use.*)
		Ts_Tf_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_Tf_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_D_Ts_Tf_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_D_Ts_Tf_dbl_2 : UDINT; (*Data for internal use.*)
		a0_dbl_1 : UDINT; (*Data for internal use.*)
		a0_dbl_2 : UDINT; (*Data for internal use.*)
		a1_dbl_1 : UDINT; (*Data for internal use.*)
		a1_dbl_2 : UDINT; (*Data for internal use.*)
		b0_dbl_1 : UDINT; (*Data for internal use.*)
		b0_dbl_2 : UDINT; (*Data for internal use.*)
		b1_dbl_1 : UDINT; (*Data for internal use.*)
		b1_dbl_2 : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRDT1_Internal_typ : 	STRUCT  (*Internal variables of function block HCRDT1().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		Tv_old : REAL; (*Data for internal use.*)
		Tf_old : REAL; (*Data for internal use.*)
		n_Avg_old : USINT; (*Data for internal use.*)
		u_Buf : ARRAY[0..99] OF REAL; (*Data for internal use.*)
		u_BufCnt : SINT; (*Data for internal use.*)
		u_Sum_dbl_1 : UDINT; (*Data for internal use.*)
		u_Sum_dbl_2 : UDINT; (*Data for internal use.*)
		u_Avg_dbl_1 : UDINT; (*Data for internal use.*)
		u_Avg_dbl_2 : UDINT; (*Data for internal use.*)
		Reset_y_old : USINT; (*Data for internal use.*)
		Reset_y_2 : USINT; (*Data for internal use.*)
		x_dbl_1 : UDINT; (*Data for internal use.*)
		x_dbl_2 : UDINT; (*Data for internal use.*)
		Tv_Tf_dbl_1 : UDINT; (*Data for internal use.*)
		Tv_Tf_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_Ts_Tf_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_Ts_Tf_dbl_2 : UDINT; (*Data for internal use.*)
		Tv_Tf_Exp_dbl_1 : UDINT; (*Data for internal use.*)
		Tv_Tf_Exp_dbl_2 : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRDT2_Internal_typ : 	STRUCT  (*Internal variables of function block HCRDT2().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		Tv_old : REAL; (*Data for internal use.*)
		T1_old : REAL; (*Data for internal use.*)
		T2_old : REAL; (*Data for internal use.*)
		n_Avg_old : USINT; (*Data for internal use.*)
		u_Buf : ARRAY[0..99] OF REAL; (*Data for internal use.*)
		u_BufCnt : SINT; (*Data for internal use.*)
		u_Sum_dbl_1 : UDINT; (*Data for internal use.*)
		u_Sum_dbl_2 : UDINT; (*Data for internal use.*)
		u_Avg_dbl_1 : UDINT; (*Data for internal use.*)
		u_Avg_dbl_2 : UDINT; (*Data for internal use.*)
		Reset_y_old : USINT; (*Data for internal use.*)
		Reset_y_2 : USINT; (*Data for internal use.*)
		x1_dbl_1 : UDINT; (*Data for internal use.*)
		x1_dbl_2 : UDINT; (*Data for internal use.*)
		x2_dbl_1 : UDINT; (*Data for internal use.*)
		x2_dbl_2 : UDINT; (*Data for internal use.*)
		Tv_T1_dbl_1 : UDINT; (*Data for internal use.*)
		Tv_T1_dbl_2 : UDINT; (*Data for internal use.*)
		Tv_T2_dbl_1 : UDINT; (*Data for internal use.*)
		Tv_T2_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_Ts_T2_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_Ts_T2_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_T1_T2_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_T1_T2_dbl_2 : UDINT; (*Data for internal use.*)
		a0_dbl_1 : UDINT; (*Data for internal use.*)
		a0_dbl_2 : UDINT; (*Data for internal use.*)
		a1_dbl_1 : UDINT; (*Data for internal use.*)
		a1_dbl_2 : UDINT; (*Data for internal use.*)
		b0_dbl_1 : UDINT; (*Data for internal use.*)
		b0_dbl_2 : UDINT; (*Data for internal use.*)
		b1_dbl_1 : UDINT; (*Data for internal use.*)
		b1_dbl_2 : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRDT2s_Internal_typ : 	STRUCT  (*Internal variables of function block HCRDT2s().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		D_old : REAL; (*Data for internal use.*)
		Tv_old : REAL; (*Data for internal use.*)
		Tf_old : REAL; (*Data for internal use.*)
		Reset_y_old : USINT; (*Data for internal use.*)
		Reset_y_2 : USINT; (*Data for internal use.*)
		x1_dbl_1 : UDINT; (*Data for internal use.*)
		x1_dbl_2 : UDINT; (*Data for internal use.*)
		x2_dbl_1 : UDINT; (*Data for internal use.*)
		x2_dbl_2 : UDINT; (*Data for internal use.*)
		Sqrt_D_1_dbl_1 : UDINT; (*Data for internal use.*)
		Sqrt_D_1_dbl_2 : UDINT; (*Data for internal use.*)
		Tv_Tf_dbl_1 : UDINT; (*Data for internal use.*)
		Tv_Tf_dbl_2 : UDINT; (*Data for internal use.*)
		Ts_Tf_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_Tf_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_D_Ts_Tf_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_D_Ts_Tf_dbl_2 : UDINT; (*Data for internal use.*)
		a0_dbl_1 : UDINT; (*Data for internal use.*)
		a0_dbl_2 : UDINT; (*Data for internal use.*)
		a1_dbl_1 : UDINT; (*Data for internal use.*)
		a1_dbl_2 : UDINT; (*Data for internal use.*)
		b0_dbl_1 : UDINT; (*Data for internal use.*)
		b0_dbl_2 : UDINT; (*Data for internal use.*)
		b1_dbl_1 : UDINT; (*Data for internal use.*)
		b1_dbl_2 : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRIT1_Internal_typ : 	STRUCT  (*Internal variables of function block HCRIT1().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		V_old : REAL; (*Data for internal use.*)
		Tn_old : REAL; (*Data for internal use.*)
		T1_old : REAL; (*Data for internal use.*)
		Set_y_old : USINT; (*Data for internal use.*)
		Set_y_2 : USINT; (*Data for internal use.*)
		x1_dbl_1 : UDINT; (*Data for internal use.*)
		x1_dbl_2 : UDINT; (*Data for internal use.*)
		x2_dbl_1 : UDINT; (*Data for internal use.*)
		x2_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_Ts_T1_dbl_2 : UDINT; (*Data for internal use.*)
		V_Tn_dbl_1 : UDINT; (*Data for internal use.*)
		V_Tn_dbl_2 : UDINT; (*Data for internal use.*)
		a0_dbl_1 : UDINT; (*Data for internal use.*)
		a0_dbl_2 : UDINT; (*Data for internal use.*)
		a1_dbl_1 : UDINT; (*Data for internal use.*)
		a1_dbl_2 : UDINT; (*Data for internal use.*)
		b0_dbl_1 : UDINT; (*Data for internal use.*)
		b0_dbl_2 : UDINT; (*Data for internal use.*)
		b1_dbl_1 : UDINT; (*Data for internal use.*)
		b1_dbl_2 : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRNotch_Internal_typ : 	STRUCT  (*Internal variables of function block HCRNotch().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		fs_dbl_1 : UDINT; (*Data for internal use.*)
		fs_dbl_2 : UDINT; (*Data for internal use.*)
		V_old : REAL; (*Data for internal use.*)
		f0_old : REAL; (*Data for internal use.*)
		B_old : REAL; (*Data for internal use.*)
		Set_y_old : USINT; (*Data for internal use.*)
		Set_y_2 : USINT; (*Data for internal use.*)
		fg_upper : REAL; (*Upper band frequency (fg_upper = f0 + B/2). Units: [Hz]. Value range: fg_upper > f0.*)
		fg_lower : REAL; (*Lower band frequency (fg_lower = f02/(f0 + B/2)). Units: [Hz]. Value range: 0 < fg_lower < f0.*)
		B_act : REAL; (*Actual effective filter band width (B_act = fg_upper - fg_lower). Units: [Hz]. Value range: B_act > 0.*)
		D : REAL; (*Damping constant (D = (fg_upper/f0 - f0/fg_upper)/2). Units: [1]. Value range: D > 0.*)
		Tf : REAL; (*Filter time constant (Tf = 1/(2텾i톐0)). Units: [s]. Value range: 0 < Tf < Ts.*)
		x1_dbl_1 : UDINT; (*Data for internal use.*)
		x1_dbl_2 : UDINT; (*Data for internal use.*)
		x2_dbl_1 : UDINT; (*Data for internal use.*)
		x2_dbl_2 : UDINT; (*Data for internal use.*)
		D_Ts_Tf_dbl_1 : UDINT; (*Data for internal use.*)
		D_Ts_Tf_dbl_2 : UDINT; (*Data for internal use.*)
		Sqrt_D_1_dbl_1 : UDINT; (*Data for internal use.*)
		Sqrt_D_1_dbl_2 : UDINT; (*Data for internal use.*)
		a0_dbl_1 : UDINT; (*Data for internal use.*)
		a0_dbl_2 : UDINT; (*Data for internal use.*)
		a1_dbl_1 : UDINT; (*Data for internal use.*)
		a1_dbl_2 : UDINT; (*Data for internal use.*)
		b0_dbl_1 : UDINT; (*Data for internal use.*)
		b0_dbl_2 : UDINT; (*Data for internal use.*)
		b1_dbl_1 : UDINT; (*Data for internal use.*)
		b1_dbl_2 : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRPT1cP_Internal_typ : 	STRUCT  (*Internal variables of function block HCRPT1cP().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		T1_intern : REAL; (*Data for internal use.*)
		nCnt : UDINT; (*Data for internal use.*)
		Set_y_old : USINT; (*Data for internal use.*)
		Set_y_2 : USINT; (*Data for internal use.*)
		x_dbl_1 : UDINT; (*Data for internal use.*)
		x_dbl_2 : UDINT; (*Data for internal use.*)
		Exp_5_dbl_1 : UDINT; (*Data for internal use.*)
		Exp_5_dbl_2 : UDINT; (*Data for internal use.*)
		a0_dbl_1 : UDINT; (*Data for internal use.*)
		a0_dbl_2 : UDINT; (*Data for internal use.*)
		b0_dbl_1 : UDINT; (*Data for internal use.*)
		b0_dbl_2 : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRJoltFree_Internal_typ : 	STRUCT  (*Internal variables of function block HCR().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		uSwitch_old : BOOL; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRFIFO_Internal_typ : 	STRUCT  (*Internal variables of function block HCR().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		t_FIFO_max : DINT; (*Data for internal use.*)
		MemSize : UDINT; (*Data for internal use.*)
		MemSize_REAL : UDINT; (*Data for internal use.*)
		Set_y_2 : BOOL; (*Data for internal use.*)
		pFIFO_Buf : UDINT; (*Data for internal use.*)
		pFIFO_OutIn : UDINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRRampGen_Internal_typ : 	STRUCT  (*Internal variables of function block HCRRampGen().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		RampGenPhase : USINT; (*Phases of the ramp generation. Value range: {0: Idle phase, 1: Rise phase, 2: Constant phase, 3: Fall phase}.*)
		t_rise : REAL; (*Data for internal use.*)
		t_hold : REAL; (*Data for internal use.*)
		t_fall : REAL; (*Data for internal use.*)
		y_start : REAL; (*Internal copy of y_start.*)
		y_hold : REAL; (*Internal copy of y_hold.*)
		y_end : REAL; (*Internal copy of y_end.*)
		y : REAL; (*Data for internal use.*)
		dy : REAL; (*Data for internal use.*)
		dy_ramped : REAL; (*Data for internal use.*)
		Finished : BOOL; (*Data for internal use.*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		Timer_dbl_1 : UDINT; (*Data for internal use.*)
		Timer_dbl_2 : UDINT; (*Data for internal use.*)
		k_Ramp_dbl_1 : UDINT; (*Data for internal use.*)
		k_Ramp_dbl_2 : UDINT; (*Data for internal use.*)
		y_dbl_1 : UDINT; (*Data for internal use.*)
		y_dbl_2 : UDINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRSPF_Internal_typ : 	STRUCT  (*Internal variables of function block HCRSPF().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		ProfileNb : USINT; (*Number of movement profiles needed to reach the end of the movement s_end. Value range: {0, 1, 2}.*)
		ProfileID : USINT; (*Movement profile ID. Value range: {0: 1. Movement profile, 1: 2. Movement profile}.*)
		MovementCase : SINT; (*Data for internal use.*)
		MovementPhase : USINT; (*Phases of the movement. Value range: {0: Idle phase; 1: Acceleration phase; 2: Constant speed phase; 3: Deceleration phase; 4,5,6: Spinout phase}.*)
		MovementStep : USINT; (*Data for internal use.*)
		s_end : REAL; (*Data for internal use.*)
		q_set_0_dbl_1 : UDINT; (*Data for internal use.*)
		q_set_0_dbl_2 : UDINT; (*Data for internal use.*)
		s_set_0_dbl_1 : UDINT; (*Data for internal use.*)
		s_set_0_dbl_2 : UDINT; (*Data for internal use.*)
		v_set_0_dbl_1 : UDINT; (*Data for internal use.*)
		v_set_0_dbl_2 : UDINT; (*Data for internal use.*)
		a_set_0_dbl_1 : UDINT; (*Data for internal use.*)
		a_set_0_dbl_2 : UDINT; (*Data for internal use.*)
		v0 : REAL; (*Data for internal use.*)
		v0_dbl_1 : UDINT; (*Data for internal use.*)
		v0_dbl_2 : UDINT; (*Data for internal use.*)
		v0_intrude : USINT; (*Data for internal use.*)
		v0_state : USINT; (*Data for internal use.*)
		q_set : REAL; (*Data for internal use.*)
		q_set_Jolt : REAL; (*Data for internal use.*)
		q_set_dbl_1 : UDINT; (*Data for internal use.*)
		q_set_dbl_2 : UDINT; (*Data for internal use.*)
		s_set : REAL; (*Data for internal use.*)
		s_set_Jolt : REAL; (*Data for internal use.*)
		s_set_dbl_1 : UDINT; (*Data for internal use.*)
		s_set_dbl_2 : UDINT; (*Data for internal use.*)
		s_set_add_dbl_1 : UDINT; (*Data for internal use.*)
		s_set_add_dbl_2 : UDINT; (*Data for internal use.*)
		v_set : REAL; (*Data for internal use.*)
		v_set_Jolt : REAL; (*Data for internal use.*)
		v_set_dbl_1 : UDINT; (*Data for internal use.*)
		v_set_dbl_2 : UDINT; (*Data for internal use.*)
		a_set : REAL; (*Data for internal use.*)
		a_set_Jolt : REAL; (*Data for internal use.*)
		a_set_dbl_1 : UDINT; (*Data for internal use.*)
		a_set_dbl_2 : UDINT; (*Data for internal use.*)
		vC_pos_dbl_1 : UDINT; (*Data for internal use.*)
		vC_pos_dbl_2 : UDINT; (*Data for internal use.*)
		vC_neg_dbl_1 : UDINT; (*Data for internal use.*)
		vC_neg_dbl_2 : UDINT; (*Data for internal use.*)
		aAcc_pos_dbl_1 : UDINT; (*Data for internal use.*)
		aAcc_pos_dbl_2 : UDINT; (*Data for internal use.*)
		aDec_pos_dbl_1 : UDINT; (*Data for internal use.*)
		aDec_pos_dbl_2 : UDINT; (*Data for internal use.*)
		aAcc_neg_dbl_1 : UDINT; (*Data for internal use.*)
		aAcc_neg_dbl_2 : UDINT; (*Data for internal use.*)
		aDec_neg_dbl_1 : UDINT; (*Data for internal use.*)
		aDec_neg_dbl_2 : UDINT; (*Data for internal use.*)
		aDec : REAL; (*Data for internal use.*)
		aDec_intrude : BOOL; (*Data for internal use.*)
		t_Jolt_max : REAL; (*Data for internal use.*)
		t_Jolt_limit : REAL; (*Data for internal use.*)
		t_Jolt : REAL; (*Internal used jolt time. Units: [s]. Value range: 0 <= t_Jolt <= 0.2.*)
		t_Jolt_dbl_1 : UDINT; (*Data for internal use.*)
		t_Jolt_dbl_2 : UDINT; (*Data for internal use.*)
		sDelta : REAL; (*Calculated position difference at the initialization (Init = 1) of a new trajectory. Units: [mm].*)
		sDelta_dbl_1 : UDINT; (*Data for internal use.*)
		sDelta_dbl_2 : UDINT; (*Data for internal use.*)
		sBrake : REAL; (*Necessary deceleration distance to brake from the current speed v_set immediately to v_set = 0. Units: [mm]. Value range: sBrake >= 0.*)
		sBrake_dbl_1 : UDINT; (*Data for internal use.*)
		sBrake_dbl_2 : UDINT; (*Data for internal use.*)
		vTop : REAL; (*Calculated top speed. Units: [mm/s]. Value range: vTop >= 0.*)
		vTop_dbl_1 : UDINT; (*Data for internal use.*)
		vTop_dbl_2 : UDINT; (*Data for internal use.*)
		MoveParaVec : ARRAY[0..5] OF REAL; (*Data for internal use.*)
		AccVec_dbl : ARRAY[0..39] OF UDINT; (*Data for internal use.*)
		ConstVec_dbl : ARRAY[0..39] OF UDINT; (*Data for internal use.*)
		DecVec_dbl : ARRAY[0..39] OF UDINT; (*Data for internal use.*)
		AccVec : ARRAY[0..19] OF REAL; (*Data for internal use.*)
		ConstVec : ARRAY[0..19] OF REAL; (*Data for internal use.*)
		DecVec : ARRAY[0..19] OF REAL; (*Data for internal use.*)
		pBuf_q_set : UDINT; (*Data for internal use.*)
		pBuf_s_set : UDINT; (*Data for internal use.*)
		pBuf_v_set : UDINT; (*Data for internal use.*)
		pBuf_a_set : UDINT; (*Data for internal use.*)
		BufCntMax : DINT; (*Data for internal use.*)
		BufCnt : DINT; (*Data for internal use.*)
		BufCnt_t_Jolt : DINT; (*Data for internal use.*)
		Cnt_t_Jolt : DINT; (*Data for internal use.*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		Ts_2_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_2_dbl_2 : UDINT; (*Data for internal use.*)
		Ts_4_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_4_dbl_2 : UDINT; (*Data for internal use.*)
		Timer : REAL; (*Data for internal use.*)
		Timer_dbl_1 : UDINT; (*Data for internal use.*)
		Timer_dbl_2 : UDINT; (*Data for internal use.*)
		Timer_Ts : REAL; (*Timer for profile generation. Units: [s]. Value range: Timer_Ts >= 0.*)
		Timer_Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Timer_Ts_dbl_2 : UDINT; (*Data for internal use.*)
		Init : BOOL; (*Data for internal use.*)
		Brake : BOOL; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		constTCycle : BOOL; (*Data for internal use.*)
		counterState : UINT; (*Data for internal use.*)
		musecs_old : UDINT; (*Data for internal use.*)
		SysTicks_old : UDINT; (*Data for internal use.*)
		Bootkey_T : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRSFG_Internal_typ : 	STRUCT  (*Internal variables of function block HCRSFG().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		SFG_Para : HCRMovePara_typ; (*Data for internal use.*)
		Profile_Case : USINT; (*Data for internal use.*)
		Fp_delta : REAL; (*Data for internal use.*)
		Fp_brake : REAL; (*Data for internal use.*)
		Fp_set_0 : REAL; (*Data for internal use.*)
		dFp_set_0 : REAL; (*Data for internal use.*)
		dFp_home : REAL; (*Data for internal use.*)
		dFp_0_intrude : USINT; (*Data for internal use.*)
		dFp_const : REAL; (*Data for internal use.*)
		dFp_const_avg : REAL; (*Data for internal use.*)
		dFp_thresh : ARRAY[0..2] OF REAL; (*Data for internal use.*)
		t_Jolt : REAL; (*Data for internal use.*)
		t_delta : REAL; (*Data for internal use.*)
		t_delta_Jolt : REAL; (*Data for internal use.*)
		t_delta_3_Jolt : REAL; (*Data for internal use.*)
		Calc_t_delta : USINT; (*Data for internal use.*)
		tx : REAL; (*Data for internal use.*)
		tx_limit : REAL; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRAutoTune_Internal_typ : 	STRUCT  (*Internal variables of function block HCR().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		E : REAL; (*Youngs modulus of oil. Units: [bar].*)
		V0_pos : REAL; (*Data for internal use.*)
		V0_pos_mod_dbl_1 : UDINT; (*Data for internal use.*)
		V0_pos_mod_dbl_2 : UDINT; (*Data for internal use.*)
		V0_neg : REAL; (*Data for internal use.*)
		V0_neg_mod_dbl_1 : UDINT; (*Data for internal use.*)
		V0_neg_mod_dbl_2 : UDINT; (*Data for internal use.*)
		s_Cyl_min_dbl_1 : UDINT; (*Data for internal use.*)
		s_Cyl_min_dbl_2 : UDINT; (*Data for internal use.*)
		s_Cyl_max_dbl_1 : UDINT; (*Data for internal use.*)
		s_Cyl_max_dbl_2 : UDINT; (*Data for internal use.*)
		h_Cyl : REAL; (*Data for internal use.*)
		h_Cyl_dbl_1 : UDINT; (*Data for internal use.*)
		h_Cyl_dbl_2 : UDINT; (*Data for internal use.*)
		E_A_pos_2_dbl_1 : UDINT; (*Data for internal use.*)
		E_A_pos_2_dbl_2 : UDINT; (*Data for internal use.*)
		E_A_neg_2_dbl_1 : UDINT; (*Data for internal use.*)
		E_A_neg_2_dbl_2 : UDINT; (*Data for internal use.*)
		s0_Cyl : REAL; (*Position of cylinder piston at which the critical natural frequency omega0_Cyl occurs. Units: [mm]. Value range: 0 <= s0_Cyl <= h_Cyl.*)
		s0_Cyl_dbl_1 : UDINT; (*Data for internal use.*)
		s0_Cyl_dbl_2 : UDINT; (*Data for internal use.*)
		c0_Cyl : REAL; (*Critical replacement spring constant is included with the resulting mass of the hydraulic system m_Cyl in the natural frequency calculation. Units: [N/m]. Value range: c0_Cyl >= 0.*)
		c0_Cyl_dbl_1 : UDINT; (*Data for internal use.*)
		c0_Cyl_dbl_2 : UDINT; (*Data for internal use.*)
		omega0_Cyl : REAL; (*Critical natural frequency of the hydraulic system. Units: [1/s]. Value range: omega0_Cyl >= 0.*)
		omega0_Cyl_dbl_1 : UDINT; (*Data for internal use.*)
		omega0_Cyl_dbl_2 : UDINT; (*Data for internal use.*)
		vCyl_sup : REAL; (*Theoretical maximum speed of movement. Units: [mm/s]. vCyl_sup = 1000 / 6 * v(pSupply_max / pDelta_nom) * max(Qnom_pos / A_Cyl_pos, Qnom_neg / A_Cyl_neg). Value range: vCyl_sup >= 0. *)
		Kp_dbl_1 : UDINT; (*Data for internal use.*)
		Kp_dbl_2 : UDINT; (*Data for internal use.*)
		Kp_physical : REAL; (*Calculated 'physical' proportional gain. Relationship between Kp and Kp_physical: Kp = Kp_physical * (s_max - s_min) / vCyl_sup. Units: [1/s].*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCROmega0_Internal_typ : 	STRUCT  (*Internal variables of function block HCR().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		E : REAL; (*Youngs modulus of oil. Units: [bar].*)
		Kp_xCorr_Lim : REAL; (*Data for internal use.*)
		A_Cyl_pos : REAL; (*Data for internal use.*)
		A_Cyl_neg : REAL; (*Data for internal use.*)
		V0_pos : REAL; (*Data for internal use.*)
		V0_neg : REAL; (*Data for internal use.*)
		h_Cyl : REAL; (*Data for internal use.*)
		x_Cyl_min_dbl_1 : UDINT; (*Data for internal use.*)
		x_Cyl_min_dbl_2 : UDINT; (*Data for internal use.*)
		x_Cyl_max_dbl_1 : UDINT; (*Data for internal use.*)
		x_Cyl_max_dbl_2 : UDINT; (*Data for internal use.*)
		E_A_pos_2_dbl_1 : UDINT; (*Data for internal use.*)
		E_A_pos_2_dbl_2 : UDINT; (*Data for internal use.*)
		E_A_neg_2_dbl_1 : UDINT; (*Data for internal use.*)
		E_A_neg_2_dbl_2 : UDINT; (*Data for internal use.*)
		x0_Cyl_dbl_1 : UDINT; (*Data for internal use.*)
		x0_Cyl_dbl_2 : UDINT; (*Data for internal use.*)
		c0_Cyl : REAL; (*Critical replacement spring constant is included with the resulting mass of the hydraulic system m_Cyl in the natural frequency calculation. Units: [N/m]. Value range: c0_Cyl >= 0.*)
		c0_Cyl_dbl_1 : UDINT; (*Data for internal use.*)
		c0_Cyl_dbl_2 : UDINT; (*Data for internal use.*)
		c_Cyl_Lim_L : REAL; (*Critical replacement spring constant of the hydraulic system at position x_Cyl_min. Units: [N/m]. Value range: c_Cyl_Lim_L >= c0_Cyl.*)
		c_Cyl_Lim_L_dbl_1 : UDINT; (*Data for internal use.*)
		c_Cyl_Lim_L_dbl_2 : UDINT; (*Data for internal use.*)
		c_Cyl_Lim_R : REAL; (*Critical replacement spring constant of the hydraulic system at position x_Cyl_max. Units: [N/m]. Value range: c_Cyl_Lim_R >= c0_Cyl.*)
		c_Cyl_Lim_R_dbl_1 : UDINT; (*Data for internal use.*)
		c_Cyl_Lim_R_dbl_2 : UDINT; (*Data for internal use.*)
		c_Cyl : REAL; (*Critical replacement spring constant of the hydraulic system whereas c_Cyl = c_Cyl(x_Cyl). Units: [N/m]. Value range: c0_Cyl <= c_Cyl <= max(c_Cyl_Lim_L, c_Cyl_Lim_R).*)
		c_Cyl_dbl_1 : UDINT; (*Data for internal use.*)
		c_Cyl_dbl_2 : UDINT; (*Data for internal use.*)
		Kp_xCorr_Lim_L : REAL; (*Data for internal use.*)
		Kp_xCorr_Lim_R : REAL; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRvyServo_Internal_typ : 	STRUCT  (*Internal variables of function block HCRvyServo().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Alpha : REAL; (*Piston area ratio. Units: [1]. Value range: -1 < Alpha <= 1.*)
		vCyl_sup : REAL; (*Theoretical maximum speed of movement. Units: [mm/s]. Value range: vCyl_sup >= 0.*)
		vCyl_max : REAL; (*Data for internal use.*)
		vCyl_sum : REAL; (*Speed of cylinder motion (vCyl_sum = vCyl_abs + vCyl_rel / 100 % * vCyl_sup). Units: [mm/s]. Value range: -vCyl_sup < vCyl_sum < vCyl_sup.*)
		vCyl_thresh : REAL; (*Threshold value for the speed of cylinder movement vCyl_sum. If |vCyl_sum| <= vCyl_thresh, then vCyl_sum remains 0. Units: [mm/s]. Valid value range: vCyl_thresh >= 0.*)
		vCyl_nOverlap_pos : REAL; (*Data for internal use.*)
		vCyl_nOverlap_neg : REAL; (*Data for internal use.*)
		vCyl_old : REAL; (*Data for internal use.*)
		pSupply_max : REAL; (*Data for internal use.*)
		pSupply : REAL; (*Data for internal use.*)
		pTank : REAL; (*Data for internal use.*)
		Qnom_pos : REAL; (*Data for internal use.*)
		Qnom_neg : REAL; (*Data for internal use.*)
		A_Cyl_pos : REAL; (*Data for internal use.*)
		A_Cyl_neg : REAL; (*Data for internal use.*)
		yValve_zero : REAL; (*Data for internal use.*)
		yValve_min : REAL; (*Data for internal use.*)
		Neg_y : BOOL; (*Data for internal use.*)
		yValve_0 : REAL; (*Data for internal use.*)
		yValve_0_dbl_1 : UDINT; (*Data for internal use.*)
		yValve_0_dbl_2 : UDINT; (*Data for internal use.*)
		K_pos_dbl_1 : UDINT; (*Data for internal use.*)
		K_pos_dbl_2 : UDINT; (*Data for internal use.*)
		K_neg_dbl_1 : UDINT; (*Data for internal use.*)
		K_neg_dbl_2 : UDINT; (*Data for internal use.*)
		kV : REAL; (*Data for internal use.*)
		kV_dbl_1 : UDINT; (*Data for internal use.*)
		kV_dbl_2 : UDINT; (*Data for internal use.*)
		k4_v_set : REAL; (*Data for internal use.*)
		K_yValve : REAL; (*Data for internal use.*)
		K_yValve_dbl_1 : UDINT; (*Data for internal use.*)
		K_yValve_dbl_2 : UDINT; (*Data for internal use.*)
		K_nOverlap_pos_dbl_1 : UDINT; (*Data for internal use.*)
		K_nOverlap_pos_dbl_2 : UDINT; (*Data for internal use.*)
		K_nOverlap_neg_dbl_1 : UDINT; (*Data for internal use.*)
		K_nOverlap_neg_dbl_2 : UDINT; (*Data for internal use.*)
		S_nOverlap_dbl_1 : UDINT; (*Data for internal use.*)
		S_nOverlap_dbl_2 : UDINT; (*Data for internal use.*)
		pDelta_min_dbl_1 : UDINT; (*Data for internal use.*)
		pDelta_min_dbl_2 : UDINT; (*Data for internal use.*)
		vCyl_sup_100_dbl_1 : UDINT; (*Data for internal use.*)
		vCyl_sup_100_dbl_2 : UDINT; (*Data for internal use.*)
		vMode : USINT; (*Data for internal use.*)
		vCyl_lim : REAL; (*Data for internal use.*)
		Update_old : USINT; (*Data for internal use.*)
		Update_2 : USINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRvyServo_Fp_Internal_typ : 	STRUCT  (*Internal variables of function block HCRvyServo_Fp().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Alpha : REAL; (*Piston area ratio. Units: [1]. Value range: -1 < Alpha <= 1.*)
		vCyl_sup : REAL; (*Theoretical maximum speed of movement. Units: [mm/s]. Value range: vCyl_sup >= 0.*)
		vCyl_max : REAL; (*Data for internal use.*)
		vCyl_sum : REAL; (*Speed of cylinder motion (vCyl_sum = vCyl_abs + vCyl_rel / 100 % * vCyl_sup). Units: [mm/s]. Value range: -vCyl_sup < vCyl_sum < vCyl_sup.*)
		vCyl_thresh : REAL; (*Threshold value for the speed of cylinder movement vCyl_sum. If |vCyl_sum| <= vCyl_thresh, then vCyl_sum remains 0. Units: [mm/s]. Valid value range: vCyl_thresh >= 0.*)
		vCyl_nOverlap_pos : REAL; (*Data for internal use.*)
		vCyl_nOverlap_neg : REAL; (*Data for internal use.*)
		vCyl_old : REAL; (*Data for internal use.*)
		pSupply_max : REAL; (*Data for internal use.*)
		pSupply : REAL; (*Data for internal use.*)
		pTank : REAL; (*Data for internal use.*)
		Qnom_pos : REAL; (*Data for internal use.*)
		Qnom_neg : REAL; (*Data for internal use.*)
		A_Cyl_pos : REAL; (*Data for internal use.*)
		A_Cyl_neg : REAL; (*Data for internal use.*)
		pCyl_pos : REAL; (*The calculated pressure for the 'positive' cylinder pressure chamber. Units: [bar]. Value range: pTank <= pCyl_pos <= pSupply.*)
		pCyl_neg : REAL; (*The calculated pressure for the 'negative' cylinder pressure chamber. Units: [bar]. Value range: pTank <= pCyl_neg <= pSupply.*)
		yValve_zero : REAL; (*Data for internal use.*)
		yValve_min : REAL; (*Data for internal use.*)
		Neg_y : BOOL; (*Data for internal use.*)
		yValve_0 : REAL; (*Data for internal use.*)
		yValve_0_dbl_1 : UDINT; (*Data for internal use.*)
		yValve_0_dbl_2 : UDINT; (*Data for internal use.*)
		Supply_Tank_pos_dbl_1 : UDINT; (*Data for internal use.*)
		Supply_Tank_pos_dbl_2 : UDINT; (*Data for internal use.*)
		Supply_Tank_neg_dbl_1 : UDINT; (*Data for internal use.*)
		Supply_Tank_neg_dbl_2 : UDINT; (*Data for internal use.*)
		Qn_pos_2_A_neg_2_dbl_1 : UDINT; (*Data for internal use.*)
		Qn_pos_2_A_neg_2_dbl_2 : UDINT; (*Data for internal use.*)
		Qn_neg_2_A_pos_2_dbl_1 : UDINT; (*Data for internal use.*)
		Qn_neg_2_A_pos_2_dbl_2 : UDINT; (*Data for internal use.*)
		Qn_pos_2_A_neg_3_dbl_1 : UDINT; (*Data for internal use.*)
		Qn_pos_2_A_neg_3_dbl_2 : UDINT; (*Data for internal use.*)
		Qn_neg_2_A_pos_3_dbl_1 : UDINT; (*Data for internal use.*)
		Qn_neg_2_A_pos_3_dbl_2 : UDINT; (*Data for internal use.*)
		K_dbl_1 : UDINT; (*Data for internal use.*)
		K_dbl_2 : UDINT; (*Data for internal use.*)
		K_pos_dbl_1 : UDINT; (*Data for internal use.*)
		K_pos_dbl_2 : UDINT; (*Data for internal use.*)
		K_neg_dbl_1 : UDINT; (*Data for internal use.*)
		K_neg_dbl_2 : UDINT; (*Data for internal use.*)
		kV : REAL; (*Data for internal use.*)
		kV_dbl_1 : UDINT; (*Data for internal use.*)
		kV_dbl_2 : UDINT; (*Data for internal use.*)
		k4_v_set : REAL; (*Data for internal use.*)
		K_yValve : REAL; (*Data for internal use.*)
		K_yValve_dbl_1 : UDINT; (*Data for internal use.*)
		K_yValve_dbl_2 : UDINT; (*Data for internal use.*)
		K_nOverlap_dbl_1 : UDINT; (*Data for internal use.*)
		K_nOverlap_dbl_2 : UDINT; (*Data for internal use.*)
		K_nOverlap_pos_dbl_1 : UDINT; (*Data for internal use.*)
		K_nOverlap_pos_dbl_2 : UDINT; (*Data for internal use.*)
		K_nOverlap_neg_dbl_1 : UDINT; (*Data for internal use.*)
		K_nOverlap_neg_dbl_2 : UDINT; (*Data for internal use.*)
		S_nOverlap_dbl_1 : UDINT; (*Data for internal use.*)
		S_nOverlap_dbl_2 : UDINT; (*Data for internal use.*)
		pCyl_pos_Numer_pos_dbl_1 : UDINT; (*Data for internal use.*)
		pCyl_pos_Numer_pos_dbl_2 : UDINT; (*Data for internal use.*)
		pCyl_neg_Numer_pos_dbl_1 : UDINT; (*Data for internal use.*)
		pCyl_neg_Numer_pos_dbl_2 : UDINT; (*Data for internal use.*)
		pCyl_pos_Numer_neg_dbl_1 : UDINT; (*Data for internal use.*)
		pCyl_pos_Numer_neg_dbl_2 : UDINT; (*Data for internal use.*)
		pCyl_neg_Numer_neg_dbl_1 : UDINT; (*Data for internal use.*)
		pCyl_neg_Numer_neg_dbl_2 : UDINT; (*Data for internal use.*)
		pCyl_Denom_dbl_1 : UDINT; (*Data for internal use.*)
		pCyl_Denom_dbl_2 : UDINT; (*Data for internal use.*)
		F_Delta_min_dbl_1 : UDINT; (*Data for internal use.*)
		F_Delta_min_dbl_2 : UDINT; (*Data for internal use.*)
		vCyl_sup_100_dbl_1 : UDINT; (*Data for internal use.*)
		vCyl_sup_100_dbl_2 : UDINT; (*Data for internal use.*)
		vMode : USINT; (*Data for internal use.*)
		vCyl_lim : REAL; (*Data for internal use.*)
		Update_old : USINT; (*Data for internal use.*)
		Update_2 : USINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRFyServo_Internal_typ : 	STRUCT  (*Internal variables of function block HCRFyServo().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		E : REAL; (*Youngs modulus of oil. Units: [bar].*)
		Alpha : REAL; (*Piston area ratio. Units: [1]. Value range: -1 < Alpha <= 1.*)
		pSupply_max : REAL; (*Data for internal use.*)
		pSupply : REAL; (*Data for internal use.*)
		pTank : REAL; (*Data for internal use.*)
		Qnom_pos : REAL; (*Data for internal use.*)
		Qnom_neg : REAL; (*Data for internal use.*)
		A_Cyl_pos : REAL; (*Data for internal use.*)
		A_Cyl_neg : REAL; (*Data for internal use.*)
		V0_pos : REAL; (*Data for internal use.*)
		V0_neg : REAL; (*Data for internal use.*)
		Neg_y : BOOL; (*Data for internal use.*)
		yValve_0 : REAL; (*Data for internal use.*)
		dF_Cyl_sup : REAL; (*Theoretical maximum rate of force increase of the cylinder. Units: [N/s]. Value range: dF_Cyl_sup >= 0.*)
		dF_Cyl_sum : REAL; (*Data for internal use.*)
		x_Cyl : REAL; (*Data for internal use.*)
		h_Cyl : REAL; (*Data for internal use.*)
		h_Cyl_dbl_1 : UDINT; (*Data for internal use.*)
		h_Cyl_dbl_2 : UDINT; (*Data for internal use.*)
		K_pos_dbl_1 : UDINT; (*Data for internal use.*)
		K_pos_dbl_2 : UDINT; (*Data for internal use.*)
		K_neg_dbl_1 : UDINT; (*Data for internal use.*)
		K_neg_dbl_2 : UDINT; (*Data for internal use.*)
		K_yValve : REAL; (*Data for internal use.*)
		K_yValve_dbl_1 : UDINT; (*Data for internal use.*)
		K_yValve_dbl_2 : UDINT; (*Data for internal use.*)
		V0_A_Cyl_pos_dbl_1 : UDINT; (*Data for internal use.*)
		V0_A_Cyl_pos_dbl_2 : UDINT; (*Data for internal use.*)
		V0_A_Cyl_neg_dbl_1 : UDINT; (*Data for internal use.*)
		V0_A_Cyl_neg_dbl_2 : UDINT; (*Data for internal use.*)
		A_Cyl_pos_1000_dbl_1 : UDINT; (*Data for internal use.*)
		A_Cyl_pos_1000_dbl_2 : UDINT; (*Data for internal use.*)
		A_Cyl_neg_1000_dbl_1 : UDINT; (*Data for internal use.*)
		A_Cyl_neg_1000_dbl_2 : UDINT; (*Data for internal use.*)
		E_10_dbl_1 : UDINT; (*Data for internal use.*)
		E_10_dbl_2 : UDINT; (*Data for internal use.*)
		pDelta_min_dbl_1 : UDINT; (*Data for internal use.*)
		pDelta_min_dbl_2 : UDINT; (*Data for internal use.*)
		dF_Cyl_sup_100_dbl_1 : UDINT; (*Data for internal use.*)
		dF_Cyl_sup_100_dbl_2 : UDINT; (*Data for internal use.*)
		K_v_Cyl : REAL; (*Data for internal use.*)
		Update_old : USINT; (*Data for internal use.*)
		Update_2 : USINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRFyServo_Fp_Internal_typ : 	STRUCT  (*Internal variables of function block HCR().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Alpha : REAL; (*Piston area ratio. Units: [1]. Value range: -1 < Alpha <= 1.*)
		pSupply_max : REAL; (*Data for internal use.*)
		pSupply : REAL; (*Data for internal use.*)
		pTank : REAL; (*Data for internal use.*)
		Qnom_pos : REAL; (*Data for internal use.*)
		Qnom_neg : REAL; (*Data for internal use.*)
		A_Cyl_pos : REAL; (*Data for internal use.*)
		A_Cyl_neg : REAL; (*Data for internal use.*)
		Neg_y : BOOL; (*Data for internal use.*)
		yValve_0 : REAL; (*Data for internal use.*)
		Supply_Tank_pos_dbl_1 : UDINT; (*Data for internal use.*)
		Supply_Tank_pos_dbl_2 : UDINT; (*Data for internal use.*)
		Supply_Tank_neg_dbl_1 : UDINT; (*Data for internal use.*)
		Supply_Tank_neg_dbl_2 : UDINT; (*Data for internal use.*)
		K_numer_dbl_1 : UDINT; (*Data for internal use.*)
		K_numer_dbl_2 : UDINT; (*Data for internal use.*)
		K_yValve : REAL; (*Data for internal use.*)
		K_yValve_dbl_1 : UDINT; (*Data for internal use.*)
		K_yValve_dbl_2 : UDINT; (*Data for internal use.*)
		F_Delta_min_dbl_1 : UDINT; (*Data for internal use.*)
		F_Delta_min_dbl_2 : UDINT; (*Data for internal use.*)
		Update_old : USINT; (*Data for internal use.*)
		Update_2 : USINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRNode_Internal_typ : 	STRUCT  (*Internal variables of a linearization node.*)
		X : REAL; (*Data for internal use.*)
		Y : REAL; (*Data for internal use.*)
		X1 : REAL; (*Data for internal use.*)
		X2 : REAL; (*Data for internal use.*)
		Rness_crit : REAL; (*Maximum smoothing factor for this node. Units: [1].*)
		X1_dbl_1 : UDINT; (*Data for internal use.*)
		X1_dbl_2 : UDINT; (*Data for internal use.*)
		X2_dbl_1 : UDINT; (*Data for internal use.*)
		X2_dbl_2 : UDINT; (*Data for internal use.*)
		deltaX_dbl_1 : UDINT; (*Data for internal use.*)
		deltaX_dbl_2 : UDINT; (*Data for internal use.*)
		deltaY_dbl_1 : UDINT; (*Data for internal use.*)
		deltaY_dbl_2 : UDINT; (*Data for internal use.*)
		k_dbl_1 : UDINT; (*Data for internal use.*)
		k_dbl_2 : UDINT; (*Data for internal use.*)
		d_dbl_1 : UDINT; (*Data for internal use.*)
		d_dbl_2 : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRLinSpline_Internal_typ : 	STRUCT  (*Internal variables of function block HCRLinSpline().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		AscendingX_o : SINT; (*Type of monotone sorting of the x coordinates for the given node vector. Value range: {-1: not sorted monotone ascending or descending, 0: sorted monotone descending, 1: sorted monotone ascending}.*)
		AscendingXs_o : SINT; (*Type of strictly monotone sorting of the x coordinates for the given node vector. Value range: {-1: not sorted strictly monotone, 0: sorted strictly monotone descending, 1: sorted strictly monotone ascending}.*)
		AscendingY_o : SINT; (*Type of monotone sorting of the y coordinates for the given node vector. Value range: {-1: not sorted monotone ascending or descending, 0: sorted monotone descending, 1: sorted monotone ascending}.*)
		AscendingYs_o : SINT; (*Type of strictly monotone sorting of the y coordinates for the given node vector. Value range: {-1: not sorted strictly monotone, 0: sorted strictly monotone descending, 1: sorted strictly monotone ascending}.*)
		AscendingX_d : SINT; (*Data for internal use.*)
		AscendingXs_d : SINT; (*Data for internal use.*)
		AscendingY_d : SINT; (*Data for internal use.*)
		AscendingYs_d : SINT; (*Data for internal use.*)
		Rness_crit : REAL; (*Maximum smoothing factor for given node vector. Units: [1]. 0 <= Rness <= Rness_crit.*)
		RnessP : REAL; (*Data for internal use.*)
		RnessR : REAL; (*Data for internal use.*)
		_Smooth1_dbl_1 : UDINT; (*Data for internal use.*)
		_Smooth1_dbl_2 : UDINT; (*Data for internal use.*)
		_1Smooth_dbl_1 : UDINT; (*Data for internal use.*)
		_1Smooth_dbl_2 : UDINT; (*Data for internal use.*)
		_1Smooth1_dbl_1 : UDINT; (*Data for internal use.*)
		_1Smooth1_dbl_2 : UDINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRLinValve_Internal_typ : 	STRUCT  (*Internal variables of function block HCRLinValve().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Neg_Qy : BOOL; (*Data for internal use.*)
		Neg_Uy : BOOL; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRPID_Internal_typ : 	STRUCT  (*Internal variables of function block HCRPID().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Ts : DINT; (*Task cycle time. Units: [탎].*)
		WX_min : REAL; (*Data for internal use.*)
		WX_max : REAL; (*Data for internal use.*)
		WX_min_max : REAL; (*Data for internal use.*)
		_100_WX_delta_dbl_1 : UDINT; (*Data for internal use.*)
		_100_WX_delta_dbl_2 : UDINT; (*Data for internal use.*)
		W_norm_dbl_1 : UDINT; (*Data for internal use.*)
		W_norm_dbl_2 : UDINT; (*Data for internal use.*)
		X_norm_dbl_1 : UDINT; (*Data for internal use.*)
		X_norm_dbl_2 : UDINT; (*Data for internal use.*)
		Invert : BOOL; (*Data for internal use.*)
		e_norm_dbl_1 : UDINT; (*Data for internal use.*)
		e_norm_dbl_2 : UDINT; (*Data for internal use.*)
		e_DTi : REAL; (*Data for internal use.*)
		Kp : REAL; (*Data for internal use.*)
		Kw : REAL; (*Data for internal use.*)
		Kp_Kw_1_dbl_1 : UDINT; (*Data for internal use.*)
		Kp_Kw_1_dbl_2 : UDINT; (*Data for internal use.*)
		Kp_intrude : REAL; (*Data for internal use.*)
		P_intrude : BOOL; (*Data for internal use.*)
		Yp_dbl_1 : UDINT; (*Data for internal use.*)
		Yp_dbl_2 : UDINT; (*Data for internal use.*)
		Ts_dbl_1 : UDINT; (*Data for internal use.*)
		Ts_dbl_2 : UDINT; (*Data for internal use.*)
		Tn_pos_dbl_1 : UDINT; (*Data for internal use.*)
		Tn_pos_dbl_2 : UDINT; (*Data for internal use.*)
		Tn_neg_dbl_1 : UDINT; (*Data for internal use.*)
		Tn_neg_dbl_2 : UDINT; (*Data for internal use.*)
		Kp_Ts_Tn_pos_dbl_1 : UDINT; (*Data for internal use.*)
		Kp_Ts_Tn_pos_dbl_2 : UDINT; (*Data for internal use.*)
		Kp_Ts_Tn_neg_dbl_1 : UDINT; (*Data for internal use.*)
		Kp_Ts_Tn_neg_dbl_2 : UDINT; (*Data for internal use.*)
		Yi_load : REAL; (*Load value for the I part. Units: [%]. Valid value range: -100 <= Yi_load <= 100.*)
		I_load : SINT; (*Trigger to load the I part (Yi) with the external value Yi_load. Valid value range: {-2, 0, 1, 2}. After loading the I part I_load is set to zero internally.*)
		Y_bias : REAL; (*Data for internal use.*)
		PID_bias : USINT; (*Data for internal use.*)
		Ypi_limit : REAL; (*Data for internal use.*)
		PI_limit : USINT; (*Data for internal use.*)
		Yi_dbl_1 : UDINT; (*Data for internal use.*)
		Yi_dbl_2 : UDINT; (*Data for internal use.*)
		Yi_pos_last_dbl_1 : UDINT; (*Data for internal use.*)
		Yi_pos_last_dbl_2 : UDINT; (*Data for internal use.*)
		Yi_neg_last_dbl_1 : UDINT; (*Data for internal use.*)
		Yi_neg_last_dbl_2 : UDINT; (*Data for internal use.*)
		I_Switch_Sign : SINT; (*Data for internal use.*)
		I_Switch : SINT; (*Data for internal use.*)
		I_Switch_old : SINT; (*Data for internal use.*)
		I_Switch_off : SINT; (*Data for internal use.*)
		d_mode : USINT; (*Data for internal use.*)
		D : REAL; (*Data for internal use.*)
		Tv_dbl_1 : UDINT; (*Data for internal use.*)
		Tv_dbl_2 : UDINT; (*Data for internal use.*)
		Tf_dbl_1 : UDINT; (*Data for internal use.*)
		Tf_dbl_2 : UDINT; (*Data for internal use.*)
		x1d_dbl_1 : UDINT; (*Data for internal use.*)
		x1d_dbl_2 : UDINT; (*Data for internal use.*)
		x2d_dbl_1 : UDINT; (*Data for internal use.*)
		x2d_dbl_2 : UDINT; (*Data for internal use.*)
		a0d_dbl_1 : UDINT; (*Data for internal use.*)
		a0d_dbl_2 : UDINT; (*Data for internal use.*)
		a1d_dbl_1 : UDINT; (*Data for internal use.*)
		a1d_dbl_2 : UDINT; (*Data for internal use.*)
		b0d_dbl_1 : UDINT; (*Data for internal use.*)
		b0d_dbl_2 : UDINT; (*Data for internal use.*)
		b1d_dbl_1 : UDINT; (*Data for internal use.*)
		b1d_dbl_2 : UDINT; (*Data for internal use.*)
		Yd_dbl_1 : UDINT; (*Data for internal use.*)
		Yd_dbl_2 : UDINT; (*Data for internal use.*)
		Reset_Yd : USINT; (*Data for internal use.*)
		Yadd : REAL; (*Data for internal use.*)
		Y_min : REAL; (*Data for internal use.*)
		Y_max : REAL; (*Data for internal use.*)
		Ytotal_dbl_1 : UDINT; (*Data for internal use.*)
		Ytotal_dbl_2 : UDINT; (*Data for internal use.*)
		Ylim_dbl_1 : UDINT; (*Data for internal use.*)
		Ylim_dbl_2 : UDINT; (*Data for internal use.*)
		Y_Fbk_ext : REAL; (*Data for internal use.*)
		Fbk_mode : USINT; (*Data for internal use.*)
		K_Fbk_Kp_dbl_1 : UDINT; (*Data for internal use.*)
		K_Fbk_Kp_dbl_2 : UDINT; (*Data for internal use.*)
		e_Fbk_dbl_1 : UDINT; (*Data for internal use.*)
		e_Fbk_dbl_2 : UDINT; (*Data for internal use.*)
		dY_max : REAL; (*Data for internal use.*)
		dY_max_Ts_dbl_1 : UDINT; (*Data for internal use.*)
		dY_max_Ts_dbl_2 : UDINT; (*Data for internal use.*)
		Y_dbl_1 : UDINT; (*Data for internal use.*)
		Y_dbl_2 : UDINT; (*Data for internal use.*)
		UpdateValid : BOOL; (*All updated parameters were valid.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey_CM : UDINT; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRP2P_Cont_Internal_typ : 	STRUCT  (*Internal variables of function block HCRP2P_Cont().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		MoveDir : SINT; (*Direction of movement (derived from the set position s_set). Value range: {-1: negative direction of movement, 0: undefined, 1: positive direction of movement}. *)
		s_set_old : REAL; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRs_Cont_Internal_typ : 	STRUCT  (*Internal variables of function block HCRs_Cont().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		vCyl_sup : REAL; (*Theoretical maximum speed of movement. Units: [mm/s]. Value range: vCyl_sup >= 0.*)
		s_set_old : REAL; (*Data for internal use.*)
		UseAsSpeedCont : BOOL; (*Data for internal use.*)
		kV : REAL; (*Data for internal use.*)
		kV_dbl_1 : UDINT; (*Data for internal use.*)
		kV_dbl_2 : UDINT; (*Data for internal use.*)
		WX_min_max : REAL; (*Data for internal use.*)
		k_v_set : ARRAY[0..1] OF REAL; (*Data for internal use.*)
		PID_s_bias : USINT; (*Data for internal use.*)
		Qy_s_bias : REAL; (*Data for internal use.*)
		yValve_bias : REAL; (*Data for internal use.*)
		K_yValve : REAL; (*Data for internal use.*)
		vCyl_bias : REAL; (*Data for internal use.*)
		vCyl_sum : REAL; (*Data for internal use.*)
		vCyl_abs : REAL; (*Data for internal use.*)
		vCyl_rel : REAL; (*Data for internal use.*)
		Y_bias : REAL; (*Data for internal use.*)
		Oset_Mode : USINT; (*Data for internal use.*)
		Qy_Oset_s_pos : REAL; (*Memory element"Oset+". Units: [l/min].*)
		Qy_Oset_s_neg : REAL; (*Memory element"Oset-". Units: [l/min].*)
		Qy_I_Switch : USINT; (*Data for internal use.*)
		Qy_I : REAL; (*Volume flow generated by the PID integrator. Units: [l/min]. Value range: -Qnom_neg <= Qy_I <= Qnom_pos.*)
		MoveDir_I : SINT; (*Direction of movement (derived from the set position s_set). Value range: {-1: negative direction of movement, 0: undefined, 1: positive direction of movement}. *)
		vMode : USINT; (*Data for internal use.*)
		v_lim : REAL; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRs_Cont_p_Internal_typ : 	STRUCT  (*Internal variables of function block HCRs_Cont_p().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		vCyl_sup : REAL; (*Theoretical maximum speed of movement. Units: [mm/s]. Value range: vCyl_sup >= 0.*)
		s_set_old : REAL; (*Data for internal use.*)
		UseAsSpeedCont : BOOL; (*Data for internal use.*)
		kV : REAL; (*Data for internal use.*)
		kV_dbl_1 : UDINT; (*Data for internal use.*)
		kV_dbl_2 : UDINT; (*Data for internal use.*)
		WX_min_max : REAL; (*Data for internal use.*)
		k_v_set : ARRAY[0..1] OF REAL; (*Data for internal use.*)
		PID_s_bias : USINT; (*Data for internal use.*)
		Qy_s_bias : REAL; (*Data for internal use.*)
		yValve_bias : REAL; (*Data for internal use.*)
		K_yValve : REAL; (*Data for internal use.*)
		vCyl_bias : REAL; (*Data for internal use.*)
		vCyl_sum : REAL; (*Data for internal use.*)
		vCyl_abs : REAL; (*Data for internal use.*)
		vCyl_rel : REAL; (*Data for internal use.*)
		Y_bias : REAL; (*Data for internal use.*)
		Oset_Mode : USINT; (*Data for internal use.*)
		Qy_Oset_s_pos : REAL; (*Memory element"Oset+". Units: [l/min].*)
		Qy_Oset_s_neg : REAL; (*Memory element"Oset-". Units: [l/min].*)
		Qy_I_Switch : USINT; (*Data for internal use.*)
		Qy_I : REAL; (*Volume flow generated by the PID integrator. Units: [l/min]. Value range: -Qnom_neg <= Qy_I <= Qnom_pos.*)
		MoveDir_I : SINT; (*Direction of movement (derived from the set position s_set). Value range: {-1: negative direction of movement, 0: undefined, 1: positive direction of movement}. *)
		vMode : USINT; (*Data for internal use.*)
		v_lim : REAL; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRF_Cont_Internal_typ : 	STRUCT  (*Internal variables of function block HCRF_Cont().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Qnom_pos : REAL; (*Data for internal use.*)
		Qnom_neg : REAL; (*Data for internal use.*)
		Oset_Mode : USINT; (*Data for internal use.*)
		Qy_Oset_F_pos : REAL; (*Memory element "Oset+". Units: [l/min].*)
		Qy_Oset_F_neg : REAL; (*Memory element "Oset-". Units: [l/min].*)
		PID_F_bias : USINT; (*Data for internal use.*)
		Qy_F_bias : REAL; (*Data for internal use.*)
		yValve_bias : REAL; (*Data for internal use.*)
		K_yValve : REAL; (*Data for internal use.*)
		u_bias : REAL; (*Data for internal use.*)
		u_sum : REAL; (*Data for internal use.*)
		u_abs : REAL; (*Data for internal use.*)
		u_rel : REAL; (*Data for internal use.*)
		Y_bias : REAL; (*Data for internal use.*)
		MoveDir : SINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRF_Cont_p_Internal_typ : 	STRUCT  (*Internal variables of function block HCRF_Cont_p().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		Qnom_pos : REAL; (*Data for internal use.*)
		Qnom_neg : REAL; (*Data for internal use.*)
		Oset_Mode : USINT; (*Data for internal use.*)
		Qy_Oset_F_pos : REAL; (*Memory element "Oset+". Units: [l/min].*)
		Qy_Oset_F_neg : REAL; (*Memory element "Oset-". Units: [l/min].*)
		PID_F_bias : USINT; (*Data for internal use.*)
		Qy_F_bias : REAL; (*Data for internal use.*)
		yValve_bias : REAL; (*Data for internal use.*)
		K_yValve : REAL; (*Data for internal use.*)
		dF_Cyl_bias : REAL; (*Data for internal use.*)
		dF_Cyl_v : REAL; (*Data for internal use.*)
		dF_Cyl_sum : REAL; (*Data for internal use.*)
		dF_Cyl_abs : REAL; (*Data for internal use.*)
		dF_Cyl_rel : REAL; (*Data for internal use.*)
		Y_bias : REAL; (*Data for internal use.*)
		MoveDir : SINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRsF_Cont_Internal_typ : 	STRUCT  (*Internal variables of function block HCRsF_Cont().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		PID_s_bias : USINT; (*Data for internal use.*)
		Qy_s_bias : REAL; (*Data for internal use.*)
		PID_F_bias : USINT; (*Data for internal use.*)
		Qy_F_bias : REAL; (*Data for internal use.*)
		tSwitch : REAL; (*Data for internal use.*)
		uSwitch_old : USINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	HCRsF_Cont_p_Internal_typ : 	STRUCT  (*Internal variables of function block HCRsF_Cont_p().*)
		statusTxt : STRING[100]; (*Function block status message as message text.*)
		CTRLmode : USINT; (*Data for internal use.*)
		F_Cont_d_mode : USINT; (*Data for internal use.*)
		F_Cont_Qy : REAL; (*Data for internal use.*)
		PID_s_bias : USINT; (*Data for internal use.*)
		Qy_s_bias : REAL; (*Data for internal use.*)
		PID_F_bias : USINT; (*Data for internal use.*)
		Qy_F_bias : REAL; (*Data for internal use.*)
		tSwitch : REAL; (*Internal copy of tSwitch. Units: [s].*)
		uSwitch_old : USINT; (*Data for internal use.*)
		enable_old : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
END_TYPE
