TYPE
	ReadControlParameterData_Req_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"195" #3"16" *)
		Attribute_ID : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"201" #3"14" *)
		Weld_Mode : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"202" #3"14" *)
	END_STRUCT;
	ReadControlParameterData_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"206" #3"16" *)
		MaxVal : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"219" #3"14" *)
		MinVal : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"220" #3"14" *)
		UnitsCode : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"221" #3"15" *)
		DecimalPlace : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"222" #3"15" *)
		Name : STRING[16];	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"223" #3"19" *)
		ReturnCode : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"225" #3"15" *)
	END_STRUCT;
	UDP_typ2 : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"49" #3"16" *)
		listener : Udp_Listener_Intrf_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"50" #3"47" *)
		send : Udp_Send_Intrf_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"51" #3"35" *)
		listener_config : Udp_Config_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"52" #3"31" *)
		internal : Udp_Internal_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"53" #3"33" *)
		ResetCmd : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"54" #3"16" *)
	END_STRUCT;
	WC_Setup_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"107" #3"16" *)
		ctrlParam : SetControlsActionRequest_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"108" #3"38" *)
		weldParam : WC_WeldSchedule_Param_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"109" #3"35" *)
	END_STRUCT;
	Arc_Link_Message_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"413" #3"16" *)
		header : Arc_Link_Header_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"414" #3"29" *)
		request : Arc_Link_Request_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"415" #3"30" *)
		response : Arc_Link_Response_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"416" #3"31" *)
	END_STRUCT;
	PendingResponse_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"419" #3"16" *)
		WriteAttribute30770 : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"420" #3"14" *)
		WriteAttribute30781 : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"421" #3"14" *)
		WriteAttribute30758 : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"422" #3"14" *)
		WriteAttribute30 : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"423" #3"14" *)
		CreateReadyReport : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"424" #3"14" *)
		CreateFaultReport : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"425" #3"14" *)
		fsSequence : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"427" #3"14" *)
		sqConfigDataSearchAction : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"428" #3"14" *)
		sqReadCoolerSens : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"429" #3"14" *)
		WriteAttribute30770Sequence : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"430" #3"14" *)
		WriteAttribute30781Sequence : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"431" #3"14" *)
		WriteAttribute30758Sequence : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"432" #3"14" *)
		WriteAttribute30Sequence : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"433" #3"14" *)
		CreateReadyReportSequence : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"434" #3"14" *)
		CreateFaultReportSequence : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"435" #3"14" *)
		CreateReadControlParamDataAction : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"436" #3"14" *)
	END_STRUCT;
	ARCLINK_PS_Cmd_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"147" #3"16" *)
		RUN : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"148" #3"14" *)
		COOLER : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"149" #3"14" *)
		RST : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"150" #3"14" *)
		Mode : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"151" #3"14" *)
		AmpSP : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"152" #3"15" *)
		BckAmpSP : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"153" #3"15" *)
		PulseFreq : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"154" #3"15" *)
		PulseWidth : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"155" #3"15" *)
		Trim : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"157" #3"15" *)
		UltimArc : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"158" #3"15" *)
		WFS : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"159" #3"15" *)
		Volts : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"160" #3"15" *)
		Pinch : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"161" #3"15" *)
		Development : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"163" #3"14" *)
		SendParam : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"164" #3"14" *)
	END_STRUCT;
	ARCLINK_PS_CNTRL_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"189" #3"16" *)
		Cmd : ARCLINK_PS_Cmd_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"190" #3"29" *)
		Fbk : ARCLINK_PS_FBK_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"191" #3"28" *)
		Int : ARCLINK_PS_INT_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"192" #3"29" *)
	END_STRUCT;
	ARCLINK_PS_FBK_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"136" #3"16" *)
		Error : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"138" #3"14" *)
		Status : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"139" #3"14" *)
		curArcVolt : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"140" #3"15" *)
		curArcAmp : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"141" #3"15" *)
		coolerSens_Status : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"142" #3"15" *)
		coolerPump_Status : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"143" #3"15" *)
	END_STRUCT;
	WC_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"126" #3"16" *)
		setup : WC_Setup_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"127" #3"22" *)
		data : WC_Data_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"128" #3"21" *)
		WC_Ready_Status : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"129" #3"14" *)
		WC_Fault_Status : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"130" #3"14" *)
	END_STRUCT;
	WC_Data_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"121" #3"16" *)
		telemetry : WC_HS_Telemetry_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"122" #3"29" *)
	END_STRUCT;
	SetControlsActionRequest_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"29" #3"16" *)
		ParameterMask : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"35" #3"15" *)
		WeldMode : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"42" #3"14" *)
		WorkPoint : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"49" #3"14" *)
		Trim : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"56" #3"14" *)
		WaveControl1 : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"63" #3"14" *)
		WaveControl2 : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"70" #3"14" *)
		WaveControl3 : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"77" #3"14" *)
		WaveControl4 : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"84" #3"14" *)
	END_STRUCT;
	ARCLINK_PS_INT_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"168" #3"16" *)
		_RUN : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"170" #3"14" *)
		_COOLER : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"171" #3"14" *)
		_RST : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"172" #3"14" *)
		_Mode : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"173" #3"14" *)
		_AmpSP : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"174" #3"15" *)
		_BckAmpSP : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"175" #3"15" *)
		_PulseFreq : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"176" #3"15" *)
		_PulseWidth : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"177" #3"15" *)
		_Trim : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"179" #3"15" *)
		_UltimArc : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"180" #3"15" *)
		_WFS : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"181" #3"15" *)
		_Volts : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"182" #3"15" *)
		_Pinch : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"183" #3"15" *)
	END_STRUCT;
	WC_HS_Telemetry_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"113" #3"16" *)
		current : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"114" #3"14" *)
		voltage : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"115" #3"14" *)
		fCurrent : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"116" #3"14" *)
		fVoltage : REAL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"117" #3"14" *)
	END_STRUCT;
	Arc_Link_Response_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"361" #3"16" *)
		ObjectCount : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"369" #3"15" *)
		Reserved : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"375" #3"15" *)
		Status : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"383" #3"15" *)
		ObjectAddress : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"390" #3"15" *)
		ResponseSize : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"397" #3"15" *)
		Reserved2 : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"403" #3"15" *)
		ResponseData : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"409" #3"14" *)
	END_STRUCT;
	Event_Report_Request_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"386" #3"16" *)
		AttributeIDNumber : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"391" #3"14" *)
		SequenceState : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"396" #3"15" *)
		PropertyIDNumber : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"401" #3"15" *)
		TriggerOptions : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"433" #3"15" *)
		Reserved : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"438" #3"15" *)
		Data : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"443" #3"15" *)
	END_STRUCT;
	Arc_Link_Misc_Setup_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"447" #3"16" *)
		running : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"448" #3"14" *)
		state : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"449" #3"15" *)
		CoolerAddr : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"450" #3"15" *)
		er : Event_Report_Request_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"451" #3"34" *)
	END_STRUCT;
	Arc_Link_Internal_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"52" #3"16" *)
		MaxMsgDataLength : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"53" #3"15" *)
		pInMsg : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"54" #3"15" *)
		InMsgLen : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"55" #3"16" *)
		pOutMsg : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"56" #3"15" *)
		OutMsgLen : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"57" #3"16" *)
		InMsgCnt : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"59" #3"16" *)
		OutMsgCnt : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"60" #3"16" *)
	END_STRUCT;
	Udp_Config_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"25" #3"16" *)
		ipAddress : STRING[20];	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"26" #3"27" *)
		port : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"27" #3"24" *)
		bufferSize : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"28" #3"23" *)
		buffer : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"29" #3"20" *)
	END_STRUCT;
	Udp_Send_Intrf_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"39" #3"16" *)
		oStatus : Udp_Status_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"40" #3"39" *)
		iSendCMD : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"41" #3"16" *)
		iIPaddress : STRING[20];	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"42" #3"19" *)
		iPort : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"43" #3"24" *)
		iBufferSize : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"44" #3"23" *)
		iBuffer : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"45" #3"20" *)
		iTxCallback : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"46" #3"23" *)
	END_STRUCT;
	Log_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"21" #3"16" *)
		log : ARRAY[0..29] OF STRING[254];	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"22" #3"16" *)
		pLog : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"23" #3"15" *)
	END_STRUCT;
	Robot_Comm_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"461" #3"16" *)
		ArcComTimer : TON;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"462" #3"17" *)
		CoolerSensPullTimer : TON;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"463" #3"17" *)
		CntrlParamReq : ReadControlParameterData_Req_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"464" #3"42" *)
		CntrlParamData : ReadControlParameterData_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"465" #3"38" *)
		CoolerSensPull_PT : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"467" #3"15" *)
		PT : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"468" #3"15" *)
		ArcLinkActive : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"469" #3"14" *)
		HeartBeat_Received : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"470" #3"14" *)
		Oneshot : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"471" #3"14" *)
		SysOn : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"472" #3"14" *)
		ClearError : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"473" #3"14" *)
		StopRespondHeartBeat : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"474" #3"14" *)
	END_STRUCT;
	ServiceID_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"139" #3"16" *)
		AttributeNumber : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"140" #3"17" *)
		StateNumber : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"141" #3"17" *)
		PropertyNumber : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"142" #3"17" *)
	END_STRUCT;
	Udp_Listener_Intrf_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"32" #3"16" *)
		oStatus : Udp_Status_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"33" #3"39" *)
		oDataLen : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"34" #3"23" *)
		iRxCallback : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"35" #3"23" *)
		iRxRingBuf : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"36" #3"23" *)
	END_STRUCT;
	Arc_Link_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"441" #3"16" *)
		bufIN : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"443" #3"20" *)
		bufOUT : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"444" #3"20" *)
		msgIN : Arc_Link_Message_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"445" #3"30" *)
		msgOUT : Arc_Link_Message_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"446" #3"30" *)
		internal : Arc_Link_Internal_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"447" #3"31" *)
		robot : Robot_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"448" #3"19" *)
		PendingResponse : PendingResponse_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"449" #3"29" *)
	END_STRUCT;
	RingBuffer : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\libRingBuffer.h" #2"16" #3"15" *)
		buffer : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\libRingBuffer.h" #2"17" #3"14" *)
		recordLength : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\libRingBuffer.h" #2"18" #3"13" *)
		recNum : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\libRingBuffer.h" #2"19" #3"13" *)
		length : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\libRingBuffer.h" #2"20" #3"13" *)
		start : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\libRingBuffer.h" #2"21" #3"13" *)
		end : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\libRingBuffer.h" #2"22" #3"13" *)
		cnt : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\libRingBuffer.h" #2"23" #3"13" *)
	END_STRUCT;
	Robot_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"477" #3"16" *)
		arclink : ArcLinkObject_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"479" #3"27" *)
		isMapped : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"483" #3"14" *)
		isMapping : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"484" #3"14" *)
		isMiscSetupOneShot : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"485" #3"14" *)
		ArcLinkActive : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"486" #3"14" *)
		isReady : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"487" #3"14" *)
		miscSetup : Arc_Link_Misc_Setup_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"488" #3"33" *)
		Intrf : Robot_Intrf_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"489" #3"25" *)
		wc : WC_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"490" #3"16" *)
		Cntrl : ARCLINK_PS_CNTRL_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"491" #3"30" *)
		Comm : Robot_Comm_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"492" #3"24" *)
		ReqDataSize : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"493" #3"14" *)
		ReqData_raw : ARRAY[0..31] OF USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"494" #3"15" *)
		ResDataSize : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"495" #3"14" *)
		ResData_raw : ARRAY[0..31] OF USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"496" #3"15" *)
		errorlog : Log_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"497" #3"17" *)
		eventlog : Log_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"498" #3"17" *)
	END_STRUCT;
	ArcLinkObject_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\ArcLinkObject.h" #2"5" #3"16" *)
		network : NetworkAttributes_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\ArcLinkObject.h" #2"6" #3"31" *)
	END_STRUCT;
	Arc_Link_Request_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"155" #3"16" *)
		TimeoutTime : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"163" #3"14" *)
		Flags : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"177" #3"15" *)
		Retries : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"184" #3"15" *)
		MessageCounter : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"193" #3"15" *)
		AddressingMode : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"209" #3"15" *)
		ConnectionID : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"222" #3"15" *)
		MaximumObjs : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"231" #3"15" *)
		ServiceID : ServiceID_typ;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"251" #3"23" *)
		SourceAddress : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"258" #3"15" *)
		DestinationAddress : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"308" #3"15" *)
		Service : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"316" #3"15" *)
		MaxResponseSize : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"323" #3"15" *)
		RequestSize : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"330" #3"15" *)
		Reserved : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"337" #3"15" *)
		OutgoingData : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"345" #3"14" *)
	END_STRUCT;
	Udp_Status_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"18" #3"16" *)
		error_number : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"19" #3"32" *)
		error : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"20" #3"16" *)
		ready : BOOL;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"21" #3"16" *)
		counts : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"22" #3"23" *)
	END_STRUCT;
	NetworkAttributes_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"86" #3"16" *)
		VendorID : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"99" #3"14" *)
		VendorName : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"113" #3"13" *)
		ModuleModelNumber : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"127" #3"13" *)
		ModuleModelName : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"141" #3"13" *)
		ClassID : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"155" #3"14" *)
		ClassName : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"169" #3"13" *)
		ClassRevision : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"183" #3"14" *)
		ClassType : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"204" #3"15" *)
		GroupSwitchSettings : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"225" #3"15" *)
		InstanceSwitchSettings : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"240" #3"15" *)
		GroupAssignments : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"261" #3"15" *)
		InstanceAssignments : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"276" #3"15" *)
		ArclinkRevision : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"291" #3"14" *)
		ReadyStatus : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"312" #3"15" *)
		FaultStatus : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"333" #3"15" *)
		SiliconSerialNumber : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"347" #3"14" *)
		NumberofEmbeddedObjects : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"361" #3"15" *)
		EmbeddedObjectNumber : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"375" #3"15" *)
		SoftwareVersion : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"390" #3"13" *)
		HardwareRevision : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"405" #3"13" *)
		DiagnosticStatus : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"420" #3"15" *)
		Reset : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"435" #3"15" *)
		BusAvailable : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"456" #3"15" *)
		Bootstrap : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"470" #3"15" *)
		ObjectIndicator : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"491" #3"15" *)
		NumberofTimesMapped : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"506" #3"15" *)
		ModuleBaseAddress : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"520" #3"15" *)
		NumberofObjectsMapped : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"534" #3"15" *)
		HBDisable : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"548" #3"15" *)
		PairedItemsCount : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\NetworkAttribute.h" #2"562" #3"14" *)
	END_STRUCT;
	Udp_Internal_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"10" #3"16" *)
		step : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"11" #3"31" *)
		UdpOpen_0 : UdpOpen;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"12" #3"24" *)
		UdpSend_0 : UdpSend;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"13" #3"24" *)
		UdpRecv_0 : UdpRecv;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"14" #3"24" *)
		UdpClose_0 : UdpClose;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\libUDP\libUDP.h" #2"15" #3"25" *)
	END_STRUCT;
	Arc_Link_Header_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"73" #3"16" *)
		Flags : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"110" #3"14" *)
		Sequence : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"118" #3"14" *)
		LastError : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"126" #3"15" *)
		DataLength : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\arclink.h" #2"133" #3"14" *)
	END_STRUCT;
	WC_WeldSchedule_Param_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"88" #3"16" *)
		WeldMode : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"89" #3"14" *)
		AttributeID : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"90" #3"14" *)
		ProcessType : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"91" #3"15" *)
		WireType : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"92" #3"15" *)
		WireSize : USINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"93" #3"15" *)
	END_STRUCT;
	Robot_Intrf_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"456" #3"16" *)
		xCMD : UINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\arclink\Robot.h" #2"457" #3"14" *)
	END_STRUCT;
	bgRingBuffer_typ : STRUCT	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"23" #3"16" *)
		bufSize : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"25" #3"13" *)
		init : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"26" #3"13" *)
		overrun : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"27" #3"13" *)
		dbgLevel : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"28" #3"13" *)
		dbgFormat : DINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"29" #3"13" *)
		ptrCircularBufferBegin : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"31" #3"13" *)
		ptrCircularBufferEnd : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"32" #3"13" *)
		ptrDataIn : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"34" #3"13" *)
		ptrDataOut : UDINT;	(* #1"C:/projects/MIG/MIG/Logical/LincolnPS/..\Lib\utilityLib\bgringbuffer.h" #2"35" #3"13" *)
	END_STRUCT;
END_TYPE
