TYPE
	LOGMGRINT_obj : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"46" #3"24" *)
		pLogID : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"48" #3"23" *)
		DataObjReady : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"49" #3"24" *)
		WriteData : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"50" #3"24" *)
		ReadData : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"51" #3"24" *)
		Create : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"52" #3"24" *)
		Status : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"53" #3"32" *)
		MaxLogs : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"54" #3"22" *)
		logBuf : ARRAY[0..56] OF SINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"55" #3"23" *)
		dbName : STRING[12];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"56" #3"28" *)
		recLen : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"57" #3"23" *)
		dwIdent : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"59" #3"41" *)
		DOCreate : DatObjCreate;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"60" #3"41" *)
		DOWrite : DatObjWrite;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"61" #3"41" *)
		DORead : DatObjRead;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"62" #3"41" *)
		DOInfo : DatObjInfo;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"63" #3"41" *)
	END_STRUCT;
	azzslimpid_par : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"122" #3"16" *)
		Y_max : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"123" #3"15" *)
		Y_min : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"124" #3"15" *)
		Kp : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"125" #3"15" *)
		Tn : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"126" #3"15" *)
		Tv : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"127" #3"15" *)
		Kfbk : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"128" #3"15" *)
	END_STRUCT;
	StateVectorProxy_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"357" #3"16" *)
		Name : STRING[15];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"358" #3"19" *)
		Indx : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"359" #3"14" *)
		simul : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"361" #3"9" *)
		testMode : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"362" #3"9" *)
		xCMD : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"363" #3"9" *)
		cmdWord : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"364" #3"9" *)
		fParam : ARRAY[0..7] OF REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"365" #3"10" *)
		Param : ARRAY[0..7] OF DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"366" #3"9" *)
		MCRReg : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"367" #3"19" *)
		StatusReg : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"368" #3"18" *)
		xCmd_busy : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"369" #3"10" *)
		InVal : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"370" #3"10" *)
		maxVel : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"371" #3"10" *)
		maxAcc : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"372" #3"10" *)
		curStep : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"373" #3"19" *)
		Mode : INT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"374" #3"17" *)
		OutVect : STATE_VECTOR_typ;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"376" #3"21" *)
		Status : INT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"377" #3"17" *)
		FbkVect : STATE_VECTOR_typ;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"378" #3"21" *)
		actPosDINT : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"379" #3"9" *)
		FbkWarning : INT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"380" #3"8" *)
		VirStatus : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"381" #3"10" *)
	END_STRUCT;
	Calib_Param_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"468" #3"16" *)
		num : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"470" #3"14" *)
		val : ARRAY[0..7] OF REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"471" #3"15" *)
	END_STRUCT;
	_int : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1975" #3"16" *)
		_pos : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1976" #3"22" *)
		_deltaPos : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1977" #3"22" *)
		_posCnt : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1978" #3"22" *)
		_floatPos : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1979" #3"23" *)
		_vel : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1980" #3"23" *)
		_amp : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1981" #3"23" *)
		_volt : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1982" #3"23" *)
		kVel : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1983" #3"23" *)
		kAcc : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1984" #3"23" *)
		kPos : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1985" #3"23" *)
		kVolt : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1986" #3"23" *)
		PVTPeriod : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1987" #3"22" *)
		Init : SINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1988" #3"22" *)
		startPos : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1989" #3"23" *)
		restartCnt : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1990" #3"22" *)
		cnt : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1991" #3"22" *)
		KickCntr : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1993" #3"22" *)
		const_PT : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1994" #3"22" *)
	END_STRUCT;
	_cfg : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1942" #3"16" *)
		units : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1943" #3"22" *)
		rev_motor : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1944" #3"23" *)
		rev_scale : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1945" #3"23" *)
		actPos2_scale : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1946" #3"23" *)
		absFbk : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1947" #3"23" *)
		absLastPos : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1948" #3"22" *)
		pAbsLastPos : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1949" #3"22" *)
		loopPeriod : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1950" #3"23" *)
		maxVel : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1951" #3"23" *)
		maxAcc : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1952" #3"23" *)
		signFilter : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1953" #3"23" *)
		satpMax : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1955" #3"23" *)
		kip : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1956" #3"23" *)
		kipMax : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1957" #3"23" *)
		kpp : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1958" #3"23" *)
		kppMax : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1959" #3"23" *)
		SATSMax : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1960" #3"23" *)
		programName : STRING[31];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1961" #3"27" *)
		HeartBeat : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1962" #3"23" *)
		PVTPeriod : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1963" #3"23" *)
		MtrType : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1964" #3"22" *)
		NotAutoDownload : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1967" #3"22" *)
		Appl_ID_adr : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1969" #3"23" *)
		AnalLimitPos : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1970" #3"32" *)
		AnalLimitNeg : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1971" #3"32" *)
	END_STRUCT;
	TML_Axis_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2023" #3"16" *)
		AxisID : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2024" #3"24" *)
		Version : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2025" #3"24" *)
		ProgramVersion : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2026" #3"24" *)
		FirmwareVersion : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2027" #3"24" *)
		Flag : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2028" #3"16" *)
		AxisState : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2029" #3"15" *)
		DriveStatusRegisterL : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2030" #3"24" *)
		DriveStatusRegisterH : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2031" #3"24" *)
		DriveErrorRegister : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2032" #3"24" *)
		PVTstatus : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2033" #3"24" *)
		DataLow : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2034" #3"24" *)
		DataHigh : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2035" #3"24" *)
		VarAddress : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2036" #3"24" *)
		SATS : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2037" #3"24" *)
		curPos : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2038" #3"28" *)
		_curPos : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2039" #3"28" *)
		_lastPos : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2040" #3"28" *)
		pointer : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2041" #3"24" *)
		deltaAPOS : INT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2042" #3"15" *)
		PointCounter : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2044" #3"24" *)
		HeartBeat : TON;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2045" #3"17" *)
		InitTmr : TON;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2046" #3"17" *)
	END_STRUCT;
	TML_MGR_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2054" #3"16" *)
		pSendData : ARRAY[0..1] OF UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2056" #3"15" *)
		pRecData : ARRAY[0..1] OF UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2057" #3"15" *)
		hrdw : ARRAY[0..1] OF TML_CHAN_HRDW_typ;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2058" #3"27" *)
		Firmware : ARRAY[0..1] OF UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2059" #3"15" *)
		BlockTrans : ARRAY[0..1] OF USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2060" #3"15" *)
		pAxis : ARRAY[0..1] OF UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2061" #3"22" *)
		pTML : ARRAY[0..1] OF UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2062" #3"17" *)
		pLog : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2063" #3"15" *)
	END_STRUCT;
	UDP_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"25" #3"16" *)
		Step : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"28" #3"10" *)
		SentCntr : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"30" #3"15" *)
		RecevCntr : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"31" #3"15" *)
		Intr : UDP_int_typ;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"33" #3"21" *)
		pSendChan : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"34" #3"24" *)
		pRecevChan : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"35" #3"24" *)
	END_STRUCT;
	TML_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1917" #3"16" *)
		pState : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1919" #3"29" *)
		Name : STRING[15];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1920" #3"19" *)
		Disable : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1921" #3"15" *)
		ProgramVersion : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1922" #3"24" *)
		FirmwareVersion : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1923" #3"24" *)
		PosFBK : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1925" #3"15" *)
		xCMD : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1926" #3"15" *)
		Status : TML_STAT_Enum;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1927" #3"23" *)
		StatusReg : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1928" #3"23" *)
		ErrorReg : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1929" #3"24" *)
		MCRReg : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1930" #3"24" *)
		Error : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1931" #3"16" *)
		EnableInp : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1932" #3"16" *)
		AnInp : ARRAY[0..1] OF UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1933" #3"24" *)
		DigInp : ARRAY[0..3] OF BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1934" #3"16" *)
		DigOut_stat : ARRAY[0..2] OF BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1935" #3"16" *)
		EStop : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1936" #3"16" *)
		_cfg : _cfg;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1973" #3"10" *)
		_int : _int;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1996" #3"10" *)
	END_STRUCT;
	AzzRamp : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"154" #3"16" *)
		x : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"156" #3"15" *)
		dy_up : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"157" #3"15" *)
		dy_down : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"158" #3"15" *)
		y_max : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"159" #3"15" *)
		y_min : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"160" #3"15" *)
		y_set : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"161" #3"15" *)
		status : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"163" #3"24" *)
		y : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"164" #3"15" *)
		dt : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"166" #3"15" *)
		y_old : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"167" #3"15" *)
		timestore1 : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"170" #3"23" *)
		enable : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"175" #3"16" *)
		set : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"176" #3"16" *)
		x_reached : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"178" #3"16" *)
		max_limit : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"179" #3"16" *)
		min_limit : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"180" #3"16" *)
	END_STRUCT;
	Analog_Out_Mem_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"114" #3"16" *)
		Value : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"115" #3"15" *)
		H_Incr : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"116" #3"15" *)
		L_Incr : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"117" #3"15" *)
	END_STRUCT;
	RS_Channel_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"126" #3"16" *)
		Status : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"127" #3"15" *)
		Data : ARRAY[0..31] OF USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"128" #3"15" *)
		Len : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"129" #3"14" *)
		Cntr : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"130" #3"15" *)
	END_STRUCT;
	AzzPID : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"117" #3"16" *)
		i_sum : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"118" #3"15" *)
		d_old : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"118" #3"22" *)
		e_fbk : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"118" #3"29" *)
		last_time : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"119" #3"14" *)
	END_STRUCT;
	ReversingRelay : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"223" #3"16" *)
		IN : Jog_Direction;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"224" #3"28" *)
	END_STRUCT;
	UDP_int_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"16" #3"16" *)
		send : UdpSend;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"18" #3"21" *)
		receive : UdpRecv;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"19" #3"21" *)
		close : UdpClose;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"20" #3"22" *)
		open : UdpOpen;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/UDP_Client.c" #2"21" #3"25" *)
	END_STRUCT;
	AzzSlimPID : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"131" #3"16" *)
		W : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"133" #3"15" *)
		X : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"134" #3"15" *)
		request : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"135" #3"23" *)
		pPar : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"136" #3"27" *)
		e : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"138" #3"15" *)
		Y : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"139" #3"15" *)
		dt : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"140" #3"15" *)
		status : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"141" #3"24" *)
		addInfo : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"142" #3"24" *)
		MovAvgFlt_inst : AzzMovAvgFlt;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"144" #3"26" *)
		PIDTune_inst : AzzPIDTune;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"145" #3"24" *)
		PID_inst : AzzPID;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"146" #3"20" *)
		requ_old : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"147" #3"23" *)
		enable : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"149" #3"16" *)
		enable_old : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"151" #3"16" *)
	END_STRUCT;
	LOGMGRCMD_obj : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"31" #3"24" *)
		scrollBy : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"33" #3"22" *)
		ScrollUp : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"34" #3"24" *)
		ScrollDwn : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"35" #3"24" *)
		LastLogs : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"36" #3"24" *)
		EnterLog : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"37" #3"24" *)
		Refresh : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"38" #3"24" *)
		PauseRefresh : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"39" #3"24" *)
		PauseLog : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"40" #3"24" *)
		PauseRefreshNewLog : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"41" #3"24" *)
		EraseAllLogs : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"42" #3"24" *)
	END_STRUCT;
	AzzMovAvgFlt : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"91" #3"16" *)
		x : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"93" #3"15" *)
		base : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"94" #3"23" *)
		status : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"96" #3"24" *)
		y : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"97" #3"15" *)
		sum_old : LREAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"99" #3"16" *)
		p_xold : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"101" #3"23" *)
		i_xold : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"102" #3"24" *)
		base_old : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"103" #3"23" *)
		bootkey_old : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"104" #3"23" *)
		enable : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"106" #3"16" *)
		enable_old : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"108" #3"16" *)
	END_STRUCT;
	TML_CHAN_HRDW_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2001" #3"16" *)
		AxisNum : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2003" #3"15" *)
		TXCountReadBack : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2005" #3"15" *)
		RXDataSize0 : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2007" #3"15" *)
		RXCount : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2008" #3"15" *)
		buff : ARRAY[0..3] OF USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2009" #3"15" *)
		RXIdent0 : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2010" #3"15" *)
		RXData0Word0 : ARRAY[0..3] OF UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2011" #3"15" *)
		TXCount : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2013" #3"15" *)
		TXDataSize : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2014" #3"15" *)
		TXIdent : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2015" #3"15" *)
		TXDataWord0 : ARRAY[0..3] OF UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2016" #3"15" *)
		_oldRxCount : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2018" #3"15" *)
		_indx : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"2019" #3"15" *)
	END_STRUCT;
	STATE_VECTOR_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"340" #3"16" *)
		x : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"343" #3"15" *)
		x2 : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"344" #3"15" *)
		vel : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"345" #3"15" *)
		acc : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"346" #3"15" *)
		amp : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"347" #3"15" *)
		volt : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"348" #3"15" *)
		softLimits : ARRAY[0..1] OF REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"349" #3"15" *)
		Center : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"351" #3"15" *)
		Status : INT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"352" #3"22" *)
		Mode : INT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"353" #3"22" *)
	END_STRUCT;
	CurCalib_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"475" #3"16" *)
		num : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"477" #3"14" *)
		Points : ARRAY[0..7] OF Calib_Param_typ;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"478" #3"25" *)
		GenSetup : ARRAY[0..7] OF DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"479" #3"14" *)
		GenFloatValue : ARRAY[0..7] OF REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"480" #3"15" *)
		GenDintValue : ARRAY[0..7] OF DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"481" #3"15" *)
	END_STRUCT;
	LOGMGR_obj : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"67" #3"24" *)
		LogView : ARRAY[0..19] OF STRING[96];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"69" #3"27" *)
		LastLog : STRING[96];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"70" #3"27" *)
		Logtxt_inp : STRING[127];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"71" #3"27" *)
		Ready : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"72" #3"27" *)
		curLog : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"73" #3"27" *)
		_int : LOGMGRINT_obj;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"74" #3"31" *)
		Cmd : LOGMGRCMD_obj;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\LoggerLib.h" #2"75" #3"31" *)
	END_STRUCT;
	Sequence : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"231" #3"16" *)
		_start : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"232" #3"16" *)
		_stop : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"233" #3"16" *)
		Start_in : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"234" #3"16" *)
		Stop_in : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"235" #3"16" *)
		Start_out : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"236" #3"16" *)
		Stop_out : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"237" #3"16" *)
		startTimer : TOF;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"238" #3"20" *)
		stopTimer : TOF;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"239" #3"20" *)
		State : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"240" #3"24" *)
	END_STRUCT;
	PermMem_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"120" #3"16" *)
		Analog_Out : ARRAY[0..63] OF Analog_Out_Mem_typ;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"121" #3"35" *)
	END_STRUCT;
	ERROR_Mgr_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"213" #3"16" *)
		Error : SINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"214" #3"14" *)
		lastItemIndx : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"215" #3"24" *)
		history : ARRAY[0..127] OF UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"216" #3"24" *)
		logs : ARRAY[0..127] OF LogItem_typ;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"217" #3"21" *)
		warnings : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"218" #3"14" *)
	END_STRUCT;
	Analog_Out_Module_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"146" #3"16" *)
		Name : STRING[80];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"147" #3"19" *)
		Min_Val : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"148" #3"15" *)
		Max_Val : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"149" #3"15" *)
	END_STRUCT;
	Indexer_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"243" #3"16" *)
		Run : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"244" #3"16" *)
		Limit_Forward : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"245" #3"16" *)
		Limit_Reverse : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"246" #3"16" *)
		Direction : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"247" #3"16" *)
		Sequence : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"248" #3"16" *)
		Start : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"249" #3"16" *)
		ManualStep : SINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"250" #3"21" *)
		Speed_Forward : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"251" #3"14" *)
		Speed_Reverse : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"252" #3"14" *)
		Speed_Jog : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"253" #3"14" *)
		Speed : INT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"254" #3"22" *)
		state : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"255" #3"23" *)
		Reverse_time : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"256" #3"14" *)
		Forward_time : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"257" #3"14" *)
		PreDly_time : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"258" #3"14" *)
		PostDly_time : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"259" #3"14" *)
		timer : TON;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"260" #3"20" *)
		period : UINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"261" #3"24" *)
	END_STRUCT;
	FILE_RW_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"431" #3"16" *)
		CMD : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"434" #3"15" *)
		Done : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"435" #3"16" *)
		Error : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"436" #3"16" *)
		FileLocked : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"437" #3"16" *)
		NewFileLoaded : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"438" #3"16" *)
		Mode : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"439" #3"15" *)
		fileName : STRING[63];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"442" #3"19" *)
		fileNewName : STRING[63];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"443" #3"19" *)
		deviceName : STRING[31];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"445" #3"19" *)
		targetDeviceName : STRING[31];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"446" #3"19" *)
		MsgText : STRING[127];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"448" #3"19" *)
		Tmr : TON;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"455" #3"17" *)
		pMem : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"458" #3"15" *)
		Len : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"459" #3"15" *)
		Offset : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"460" #3"15" *)
	END_STRUCT;
	AzzPIDTune : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"112" #3"16" *)
		nothing : REAL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"113" #3"15" *)
	END_STRUCT;
	LogItem_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"198" #3"16" *)
		timeStamp : DINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"200" #3"21" *)
		status : INT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"201" #3"22" *)
		value : UDINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"202" #3"23" *)
		txt : STRING[31];	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"203" #3"20" *)
	END_STRUCT;
	EditBox_typ : STRUCT	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"135" #3"16" *)
		H_Incr_Plus_Btn : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"136" #3"16" *)
		L_Incr_Plus_Btn : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"137" #3"16" *)
		H_Incr_Minus_Btn : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"138" #3"16" *)
		L_Incr_Minus_Btn : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"139" #3"16" *)
		Return_Btn : BOOL;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"140" #3"16" *)
		Cmd : USINT;	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"142" #3"15" *)
	END_STRUCT;
END_TYPE
TYPE
	TML_STAT_Enum :
 	(	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1890" #3"14" *)
		TML_STAT_DRIVE_ERR := -4,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1892" #3"9" *)
		TML_STAT_VER_ERR := -3,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1893" #3"9" *)
		TML_STAT_INIT := -2,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1894" #3"9" *)
		TML_HEARTBEAT_ERR := -1,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1895" #3"9" *)
		TML_STAT_DEAD := 0,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1896" #3"9" *)
		TML_STAT_READY := 1,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1897" #3"9" *)
		TML_STAT_IDLE := 2,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1898" #3"9" *)
		TML_STAT_HOLD_INIT := 3,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1899" #3"9" *)
		TML_STAT_HOLD_OK := 4,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1900" #3"9" *)
		TML_STAT_POS_MODE_INIT := 5,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1901" #3"9" *)
		TML_STAT_POS_MODE_OK := 6,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1902" #3"9" *)
		TML_STAT_VEL_MODE_INIT := 7,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1903" #3"9" *)
		TML_STAT_VEL_MODE_OK := 8,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1904" #3"9" *)
		TML_STAT_TORQ_MODE_INIT := 9,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1905" #3"9" *)
		TML_STAT_TORQ_MODE_OK := 10,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1906" #3"9" *)
		TML_STAT_VOLT_MODE_INIT := 11,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1907" #3"9" *)
		TML_STAT_VOLT_MODE_OK := 12,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1908" #3"9" *)
		TML_STAT_PT_MODE_INIT := 13,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1909" #3"9" *)
		TML_STAT_PT_MODE_OK := 14,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1910" #3"9" *)
		TML_STAT_CUSTOM_INIT := 15,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1911" #3"9" *)
		TML_STAT_CUSTOM_OK := 16,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1912" #3"9" *)
		TML_STAT_DRIVE_SELF_CNTRL := 17	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\Lib\WSI_types.h" #2"1913" #3"9" *)
	);
	Jog_Direction :
 	(	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"217" #3"14" *)
		Stop := 0,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"218" #3"9" *)
		Forward := 1,	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"219" #3"9" *)
		Reverse := 2	(* #1"C:/projects/RemWeld/RemWeld/Logical/UDP_Client/..\GlobalDef.h" #2"220" #3"9" *)
	);
END_TYPE
